k2-fsa/icefall

- egs/librispeech/ASR/conformer_ctc/decode.py
- egs/librispeech/ASR/tdnn_lstm_ctc/decode.py
> Fix an error in displaying decoding process.

- docs/source/installation/index.rst
- docs/source/recipes/librispeech/conformer_ctc.rst
Have changed 'AS' to 'ASR', 'pretraind' to 'pretrained'.
> Correct some spelling mistakes

- docs/source/contributing/how-to-create-a-recipe.rst
Have changed 'tourch' to 'touch'.
> Fix a spelling mistake (tourch->touch).

- egs/librispeech/ASR/RESULTS.md
- egs/librispeech/ASR/tdnn_lstm_ctc/asr_datamodule.py
@pkufool  Please have a review.
> Add commands for reproducing.

- .github/workflows/test.yml
- egs/librispeech/ASR/conformer_ctc/decode.py
- egs/librispeech/ASR/tdnn_lstm_ctc/decode.py
> Change default value of lattice-score-scale from 1.0 to 0.5

- .github/workflows/run-yesno-recipe.yml
- .github/workflows/test.yml
- egs/librispeech/ASR/local/compile_hlg.py
- egs/yesno/ASR/local/compile_hlg.py
- icefall/decode.py
- icefall/utils.py
See https://github.com/k2-fsa/k2/pull/825
> update api for RaggedTensor

- .github/workflows/run-pretrained.yml
- .github/workflows/run-yesno-recipe.yml
- .github/workflows/test.yml
- egs/librispeech/ASR/conformer_ctc/label_smoothing.py
- egs/librispeech/ASR/conformer_ctc/test_label_smoothing.py
- egs/librispeech/ASR/conformer_ctc/transformer.py
See https://github.com/k2-fsa/icefall/issues/107
This PR modifies custom LabelSmoothing to match the implementation in PyTorch and in the original paper.
> New label smoothing

- egs/librispeech/ASR/conformer_ctc/train.py
- icefall/env.py
We are using multiple machines to do various experiments. It makes
life easier to know which experiment is running on which machine
if we also log the IP and hostname of the machine.
> Print hostname and IP address to the log.

- egs/aishell/ASR/RESULTS.md
- egs/aishell/ASR/conformer_mmi/asr_datamodule.py
- egs/aishell/ASR/conformer_mmi/conformer.py
- egs/aishell/ASR/conformer_mmi/decode.py
- egs/aishell/ASR/conformer_mmi/label_smoothing.py
- egs/aishell/ASR/conformer_mmi/subsampling.py
- egs/aishell/ASR/conformer_mmi/train.py
- egs/aishell/ASR/conformer_mmi/transformer.py
- egs/aishell/ASR/local/convert_transcript_words_to_tokens.py
- egs/aishell/ASR/local/generate_unique_lexicon.py
- egs/aishell/ASR/prepare.sh
1. add phone based LF-MMI  training to AIShell recipe
2. AIShell CER is 5.12 (old recipe in snowfall is 6.28)
> add phone based LF-MMI  training to AIShell recipe

- egs/yesno/ASR/local/compute_fbank_yesno.py
Making things compatible with Lhotse PR https://github.com/lhotse-speech/lhotse/pull/525
Only yesno needed adaptation because it's 8kHz sampling rate, all the other recipes have 16kHz which is the default.
> Update feature config (compatible with Lhotse PR #525)

- egs/librispeech/ASR/conformer_ctc/train.py
closing https://github.com/k2-fsa/icefall/issues/203
> Fix librispeech train.py

- icefall/decode.py
> Incremental pruning threshold

- README.md
- egs/aishell/ASR/RESULTS.md
- egs/aishell/ASR/transducer_stateless/decode.py
- egs/aishell/ASR/transducer_stateless/model.py
- egs/aishell/ASR/transducer_stateless/train.py
update aishell-1 recipe with k2.rnnt_loss and a better result (5.7 -> 5.4 ) with same number epochs compare to torchaudio.functional.rnnt_loss.
@csukuangfj  ready for review, thanks.
> update aishell-1 recipe with k2.rnnt_loss

- README.md
- egs/aishell/ASR/RESULTS.md
- egs/aishell/ASR/transducer_stateless/model.py
1. just remove unnecessary 'torch.sum'
2. update result with more epoch
> minor fix for aishell recipe

- egs/librispeech/ASR/transducer_stateless/conformer.py
- egs/librispeech/ASR/transducer_stateless/test_conformer.py
The refactor for conformer is from https://github.com/k2-fsa/icefall/pull/228
Closes #228
> Refactor conformer.

- .github/workflows/run-librispeech-2022-03-12.yml
- .github/workflows/run-pretrained-conformer-ctc.yml
- .github/workflows/run-pretrained-transducer-stateless-librispeech-100h.yml
- .github/workflows/run-pretrained-transducer-stateless-librispeech-multi-datasets.yml
- .github/workflows/run-pretrained-transducer-stateless-modified-2-aishell.yml
- .github/workflows/run-pretrained-transducer-stateless-modified-aishell.yml
- .github/workflows/run-pretrained-transducer-stateless.yml
- .github/workflows/run-pretrained-transducer.yml
- .github/workflows/run-yesno-recipe.yml
- requirements-ci.txt
@pzelasko You may find this PR and the following references useful:
- https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows
- https://github.com/actions/cache
- https://github.com/actions/setup-python#caching-packages-dependencies
> Cache pip packages for GitHub actions

- egs/librispeech/ASR/pruned_transducer_stateless/decode.py
- egs/librispeech/ASR/pruned_transducer_stateless/train.py
- egs/librispeech/ASR/tdnn_lstm_ctc/asr_datamodule.py
- icefall/checkpoint.py
Fixes https://github.com/lhotse-speech/lhotse/issues/627
> Periodically saving checkpoint after processing given number of batches

- egs/librispeech/ASR/pruned_transducer_stateless/train.py
Fixes https://github.com/k2-fsa/icefall/pull/259#issuecomment-1075884498
Let me test it first before merging.
> Minor fixes for saving checkpoints.

- egs/librispeech/ASR/local/compute_fbank_librispeech.py
- egs/librispeech/ASR/local/compute_fbank_musan.py
- egs/librispeech/ASR/transducer/beam_search.py
- egs/librispeech/ASR/transducer/model.py
- egs/librispeech/ASR/transducer_lstm/beam_search.py
- egs/librispeech/ASR/transducer_lstm/model.py
- egs/librispeech/ASR/transducer_stateless/beam_search.py
- egs/librispeech/ASR/transducer_stateless/conformer.py
- egs/librispeech/ASR/transducer_stateless/decoder.py
- egs/librispeech/ASR/transducer_stateless/model.py
this applies a floor/min per dimension after the linear projection and before the attention (query/key/value) computation.
> Attention floor

- egs/librispeech/ASR/pruned_transducer_stateless2/model.py
- egs/librispeech/ASR/pruned_transducer_stateless2/train.py
Add mix precision training support for https://github.com/k2-fsa/icefall/pull/288.
**Note:** I only verified the code before the new learning rate scheduler was added. 
For the mix precision training for the latest code, I only ran 1 epoch on libri-100 to make sure it works.
> Support mix precision training on the reworked model

- egs/librispeech/ASR/pruned_transducer_stateless2/scaling.py
- icefall/diagnostics.py
> fix comments

- egs/librispeech/ASR/transducer/decoder.py
- egs/librispeech/ASR/transducer_lstm/decoder.py
- egs/yesno/ASR/transducer/decoder.py
Fix some typos.
https://github.com/k2-fsa/icefall/issues/328#issue-1211934509
> Fix some typos.

- egs/librispeech/ASR/pruned_transducer_stateless2/train.py
librispeech pruned stateless transducer 2
> fix fp16 option in example usage

- egs/librispeech/ASR/pruned_transducer_stateless2/decode.py
> Support specifying iteration number of checkpoints for decoding.

- egs/librispeech/ASR/pruned_transducer_stateless2/train.py
See https://github.com/k2-fsa/icefall/pull/343#discussion_r866663906
> Save batch to disk on exception.

- .github/scripts/download-gigaspeech-dev-test-dataset.sh
- .github/scripts/run-gigaspeech-pruned-transducer-stateless2-2022-05-12.sh
- .github/workflows/run-gigaspeech-2022-05-13.yml
In case the code is outdated, GitHub actions will fail and we can update the code accordingly.
> Decode gigaspeech in GitHub actions

- .github/scripts/run-librispeech-pruned-transducer-stateless3-2022-05-13.sh
- .github/workflows/run-librispeech-2022-04-29.yml
- .github/workflows/run-librispeech-pruned-transducer-stateless3-2022-05-13.yml
- README.md
- egs/librispeech/ASR/RESULTS.md
- egs/librispeech/ASR/pruned_transducer_stateless/pretrained.py
- egs/librispeech/ASR/pruned_transducer_stateless2/pretrained.py
- egs/librispeech/ASR/pruned_transducer_stateless3/pretrained.py
- egs/librispeech/ASR/pruned_transducer_stateless3/train.py
Use `--giga-prob 0.9` and make the gigaspeech XL cutset repeat itself indefinitiely so that it never exhausts.
A new epoch begins only when the LibriSpeech dataloader reaches the end.
Here are the results
|                                     | test-clean | test-other | comment                                                                       |
|-------------------------------------|------------|------------|---------------------------------------------|
| greedy search (max sym per frame 1) | 2.03       | 4.70       | --iter 1224000 --avg 14  --max-duration 600 |
| modified beam search                | 2.00       | 4.63       | --iter 1224000 --avg 14  --max-duration 600 |
| fast beam search                    | 2.10       | 4.68       | --iter 1224000 --avg 14 --max-duration 600 | …
> Update results for libri+giga multi dataset setup.

- README.md
- egs/gigaspeech/ASR/README.md
- egs/gigaspeech/ASR/RESULTS.md
- egs/gigaspeech/ASR/pruned_transducer_stateless2/decode.py
- egs/gigaspeech/ASR/pruned_transducer_stateless2/export.py
This is based on fixes in #361
> Update GigaSpeech reults

- .github/workflows/test.yml
- egs/librispeech/ASR/pruned_transducer_stateless/export.py
- egs/librispeech/ASR/pruned_transducer_stateless/test_decoder.py
- egs/librispeech/ASR/pruned_transducer_stateless/test_model.py
- egs/librispeech/ASR/pruned_transducer_stateless2/conformer.py
- egs/librispeech/ASR/pruned_transducer_stateless2/export.py
- egs/librispeech/ASR/pruned_transducer_stateless2/scaling.py
- egs/librispeech/ASR/pruned_transducer_stateless2/test_model.py
- egs/librispeech/ASR/pruned_transducer_stateless3/export.py
- egs/librispeech/ASR/pruned_transducer_stateless3/test_model.py
- egs/librispeech/ASR/pruned_transducer_stateless3/test_scaling.py
- egs/librispeech/ASR/pruned_transducer_stateless4/test_model.py
- egs/librispeech/ASR/transducer_lstm/encoder.py
- egs/librispeech/ASR/transducer_lstm/model.py
- egs/librispeech/ASR/transducer_stateless/conformer.py
- egs/librispeech/ASR/transducer_stateless/export.py
- egs/librispeech/ASR/transducer_stateless/joiner.py
- egs/librispeech/ASR/transducer_stateless/test_model.py
- egs/librispeech/ASR/transducer_stateless2/export.py
- egs/librispeech/ASR/transducer_stateless2/joiner.py
- egs/librispeech/ASR/transducer_stateless2/test_model.py
- egs/librispeech/ASR/transducer_stateless_multi_datasets/export.py
With this PR, pretrained RNN-T models can be exported via torchscript.
> Various fixes to support torch script.

- .flake8
- egs/spgispeech/ASR/local/compute_fbank_musan.py
- egs/spgispeech/ASR/local/compute_fbank_spgispeech.py
- egs/spgispeech/ASR/local/prepare_splits.py
- egs/yesno/ASR/local/compute_fbank_yesno.py
- icefall/diagnostics.py
I take some time to do some coding style checks for the latest files.
> [Ready to merge] Do some coding style checks for the latest files

- .flake8
- egs/librispeech/ASR/transducer_emformer/client/index.html
- egs/librispeech/ASR/transducer_emformer/client/main.js
- egs/librispeech/ASR/transducer_emformer/client/nav-partial.html
- egs/librispeech/ASR/transducer_emformer/client/record.html
- egs/librispeech/ASR/transducer_emformer/client/record.js
- egs/librispeech/ASR/transducer_emformer/client/upload.html
- egs/librispeech/ASR/transducer_emformer/client/upload.js
- egs/librispeech/ASR/transducer_emformer/server.py
- egs/librispeech/ASR/transducer_emformer/streaming_decode.py
- egs/librispeech/ASR/transducer_emformer/train.py
It supports reading a wav file from the client and sends it to the server for recognition at present.
Note: Even though we send all the samples at once, the server supports accepting samples coming in a streaming fashion.
https://user-images.githubusercontent.com/5284924/167114390-de28e2c7-4f97-4641-b5ff-bfe71f0554e8.mov
> First attempt to add WEB client to the streaming emformer.

- egs/aidatatang_200zh/ASR/local/compute_fbank_aidatatang_200zh.py
- egs/alimeeting/ASR/local/compute_fbank_alimeeting.py
Because there are some changes in lhotse, so I do add prefix and suffix to adapt it.
> [Ready to merge] Add prefix for compute fbank

- egs/wenetspeech/ASR/pruned_transducer_stateless2/decode.py
It is to do a change for `wenetspeech/pruned_transducer_stateless2/decode.py` .
> [Ready to merge] Do a change for wenetspeech/pruned_transducer_stateless2/decode.py

- egs/wenetspeech/ASR/local/text2segments.py
fix #406 
By the remind from the issue #406, I do a correction for text2segmentation.py in wenetspeech recipe.
> A correction for text2segmentation.py

- egs/aidatatang_200zh/ASR/local/compute_fbank_aidatatang_200zh.py
- egs/aishell/ASR/local/compute_fbank_aidatatang_200zh.py
- egs/aishell/ASR/local/compute_fbank_aishell.py
- egs/alimeeting/ASR/local/compute_fbank_alimeeting.py
- egs/librispeech/ASR/local/compute_fbank_librispeech.py
- egs/librispeech/ASR/local/compute_fbank_musan.py
- egs/spgispeech/ASR/local/compute_fbank_musan.py
- egs/spgispeech/ASR/local/compute_fbank_spgispeech.py
- egs/tedlium3/ASR/local/compute_fbank_tedlium.py
- egs/timit/ASR/local/compute_fbank_timit.py
- egs/wenetspeech/ASR/local/compute_fbank_wenetspeech_splits.py
- egs/yesno/ASR/local/compute_fbank_yesno.py
LilcomChunkyWriter has [a similar performance](https://github.com/lhotse-speech/lhotse/pull/737#issuecomment-1149412038) as ChunkedLilcomHdf5Writer but it does not depend on libhdf5.
> Replace ChunkedLilcomHdf5Writer with LilcomChunkyWriter.

- egs/aidatatang_200zh/ASR/pruned_transducer_stateless2/asr_datamodule.py
- egs/aishell/ASR/tdnn_lstm_ctc/asr_datamodule.py
- egs/aishell/ASR/transducer_stateless_modified-2/train.py
- egs/alimeeting/ASR/pruned_transducer_stateless2/asr_datamodule.py
- egs/gigaspeech/ASR/conformer_ctc/asr_datamodule.py
- egs/gigaspeech/ASR/pruned_transducer_stateless2/asr_datamodule.py
- egs/librispeech/ASR/pruned_transducer_stateless3/train.py
- egs/librispeech/ASR/tdnn_lstm_ctc/asr_datamodule.py
- egs/librispeech/ASR/transducer_stateless_multi_datasets/test_asr_datamodule.py
- egs/librispeech/ASR/transducer_stateless_multi_datasets/train.py
- egs/spgispeech/ASR/pruned_transducer_stateless2/asr_datamodule.py
- egs/tedlium3/ASR/transducer_stateless/asr_datamodule.py
- egs/timit/ASR/tdnn_lstm_ctc/asr_datamodule.py
- egs/wenetspeech/ASR/pruned_transducer_stateless2/asr_datamodule.py
See discussions at https://github.com/lhotse-speech/lhotse/pull/737
Using `load_manifest_lazy()` for MUSAN slows down the training significantly.
> Replace load_manifest_lazy with load_manifest for MUSAN.

- README.md
- egs/librispeech/ASR/RESULTS.md
Add links to https://github.com/k2-fsa/sherpa
> Add links to sherpa.

- egs/aidatatang_200zh/ASR/pruned_transducer_stateless2/export.py
- egs/aishell/ASR/transducer_stateless/export.py
- egs/aishell/ASR/transducer_stateless_modified-2/export.py
- egs/aishell/ASR/transducer_stateless_modified/export.py
- egs/aishell4/ASR/pruned_transducer_stateless5/export.py
- egs/alimeeting/ASR/pruned_transducer_stateless2/export.py
- egs/gigaspeech/ASR/pruned_transducer_stateless2/export.py
- egs/spgispeech/ASR/pruned_transducer_stateless2/export.py
- egs/tedlium3/ASR/pruned_transducer_stateless/export.py
- egs/tedlium3/ASR/transducer_stateless/export.py
- egs/wenetspeech/ASR/pruned_transducer_stateless2/export.py
This PR is to update the export.py for all recipe and make them keep the same with librispeech/ASR/*/export.py.
> [Ready to merge] Do some changes for export.py

- .github/scripts/run-aishell-pruned-transducer-stateless3-2022-06-20.sh
- .github/workflows/run-aishell-2022-06-20.yml
- egs/aishell/ASR/README.md
- egs/aishell/ASR/RESULTS.md
- egs/aishell/ASR/pruned_transducer_stateless3/aidatatang_200zh.py
- egs/aishell/ASR/pruned_transducer_stateless3/aishell.py
- egs/aishell/ASR/pruned_transducer_stateless3/asr_datamodule.py
- egs/aishell/ASR/pruned_transducer_stateless3/beam_search.py
- egs/aishell/ASR/pruned_transducer_stateless3/conformer.py
- egs/aishell/ASR/pruned_transducer_stateless3/decode.py
- egs/aishell/ASR/pruned_transducer_stateless3/decoder.py
- egs/aishell/ASR/pruned_transducer_stateless3/encoder_interface.py
- egs/aishell/ASR/pruned_transducer_stateless3/exp-context-size-1
- egs/aishell/ASR/pruned_transducer_stateless3/export.py
- egs/aishell/ASR/pruned_transducer_stateless3/joiner.py
- egs/aishell/ASR/pruned_transducer_stateless3/model.py
- egs/aishell/ASR/pruned_transducer_stateless3/optim.py
- egs/aishell/ASR/pruned_transducer_stateless3/pretrained.py
- egs/aishell/ASR/pruned_transducer_stateless3/scaling.py
- egs/aishell/ASR/pruned_transducer_stateless3/train.py
- egs/librispeech/ASR/pruned_transducer_stateless2/decoder.py
- egs/librispeech/ASR/pruned_transducer_stateless5/conformer.py
Using [aidatatang_200zh](https://openslr.org/62/) as extra training data.
> Add pruned RNN-T for aishell.

- egs/ptb/LM/local/prepare_lm_training_data.py
- egs/ptb/LM/local/train_bpe_model.py
I find some errors about the soft connection path in egs/ptb/LM/local #439 . So I correct it.
> Fix errors for soft connection in egs/ptb/LM/local

- egs/wenetspeech/ASR/local/compute_fbank_wenetspeech_dev_test.py
- egs/wenetspeech/ASR/local/compute_fbank_wenetspeech_splits.py
As a response and solution for [#761](https://github.com/lhotse-speech/lhotse/issues/761).
> Mv split cuts before computing feature

- egs/librispeech/ASR/distillation_with_hubert.sh
- egs/librispeech/ASR/pruned_transducer_stateless6/model.py
- egs/librispeech/ASR/pruned_transducer_stateless6/train.py
1. now toolkit "quantization" is renamed to " multi_quantization"  and released to pypi.
> update multi_quantization installation

- egs/librispeech/ASR/pruned_transducer_stateless3/decode.py
I think the error was introduced by https://github.com/k2-fsa/icefall/pull/471
> Fix using G before assignment in pruned_transducer_stateless/decode.py

- egs/aishell/ASR/pruned_transducer_stateless3/decode.py
- egs/aishell/ASR/pruned_transducer_stateless3/export.py
- egs/aishell/ASR/pruned_transducer_stateless3/pretrained.py
PR #495 introduces an error. This commit fixes it.
> Fix get_transducer_model() for aishell.

- icefall/decode.py
detailed in https://github.com/k2-fsa/k2/pull/1028
> liear_fst_with_self_loops

- .github/scripts/run-librispeech-pruned-transducer-stateless3-2022-05-13.sh
- egs/librispeech/ASR/pruned_transducer_stateless3/export.py
- egs/librispeech/ASR/pruned_transducer_stateless3/onnx_check_all_in_one.py
- requirements-ci.txt
- requirements.txt
1. added onnx all-in-one exporting part to `export.py`
2. created `onnx_check_all_in_one.py`
> Merging onnx models

- egs/librispeech/ASR/pruned_transducer_stateless/model.py
- egs/librispeech/ASR/pruned_transducer_stateless/train.py
- egs/librispeech/ASR/pruned_transducer_stateless2/train.py
- egs/librispeech/ASR/pruned_transducer_stateless3/model.py
- egs/librispeech/ASR/pruned_transducer_stateless3/train.py
- egs/librispeech/ASR/pruned_transducer_stateless4/train.py
- egs/librispeech/ASR/pruned_transducer_stateless5/train.py
- egs/librispeech/ASR/pruned_transducer_stateless6/model.py
- egs/librispeech/ASR/pruned_transducer_stateless6/train.py
- icefall/utils.py
Propagate changes made by @csukuangfj in [https://github.com/k2-fsa/icefall/pull/525](url) to other LibriSpeech recipes. It filters out infinite numbers during loss computation.
> propagate changes from #525 to other librispeech recipes

- egs/aishell/ASR/conformer_ctc/decode.py
- egs/aishell/ASR/conformer_mmi/decode.py
- egs/aishell/ASR/pruned_transducer_stateless3/decode.py
- egs/aishell/ASR/tdnn_lstm_ctc/decode.py
- egs/aishell/ASR/transducer_stateless/decode.py
- egs/aishell/ASR/transducer_stateless_modified-2/decode.py
- egs/aishell/ASR/transducer_stateless_modified/decode.py
- egs/spgispeech/ASR/pruned_transducer_stateless2/decode.py
The bug was introduced by this PR https://github.com/k2-fsa/icefall/pull/522
> Fix not enough values to unpack error .

- egs/timit/ASR/tdnn_lstm_ctc/asr_datamodule.py
> very minor change in timit asr_datamodule.py

- egs/librispeech/ASR/distillation_with_hubert.sh
- egs/librispeech/ASR/pruned_transducer_stateless6/vq_utils.py
Signed-off-by: shanguanma <nanr9544@gmail.com>
> fixed import quantization is none

- egs/alimeeting/ASR/local/compute_fbank_alimeeting.py
- egs/alimeeting/ASR/local/text2segments.py
- egs/alimeeting/ASR/prepare.sh
- egs/timit/ASR/tdnn_lstm_ctc/asr_datamodule.py
minor changes for correct path names && import module text2segments.py (in alimeeting recipe)
> minor changes for correct path names && import module text2segments.py

- egs/tedlium3/ASR/local/prepare_lexicon.py
- egs/tedlium3/ASR/local/prepare_transcripts.py
This PR fixes FileNotFoundError in tedlium3 recipe.
> Modified prepare_transcripts.py and preprare_lexicon.py of tedlium3 recipe

- .github/workflows/style_check.yml
- requirements.txt
See https://github.com/lhotse-speech/lhotse/pull/844#issuecomment-1273419055
> Add dill to requirements.txt

- .github/scripts/run-pre-trained-conformer-ctc.sh
- .github/scripts/run-wenetspeech-pruned-transducer-stateless2.sh
- .github/workflows/run-wenetspeech-pruned-transducer-stateless2.yml
- egs/librispeech/ASR/pruned_transducer_stateless3/export.py
- egs/wenetspeech/ASR/pruned_transducer_stateless2/export.py
- egs/wenetspeech/ASR/pruned_transducer_stateless2/jit_pretrained.py
- egs/wenetspeech/ASR/pruned_transducer_stateless2/onnx_check.py
- egs/wenetspeech/ASR/pruned_transducer_stateless2/onnx_pretrained.py
- egs/wenetspeech/ASR/pruned_transducer_stateless2/pretrained.py
- egs/wenetspeech/ASR/pruned_transducer_stateless2/scaling_converter.py
You can find the exported ONNX models trained by the wenetspeech at the following repo:
https://huggingface.co/luomingshuang/icefall_asr_wenetspeech_pruned_transducer_stateless2/tree/main/exp
---
https://github.com/k2-fsa/sherpa-onnx
shows how to use the exported model for speech recognition.
> Support exporting to ONNX for the wenetspeech recipe

- egs/librispeech/ASR/RESULTS.md
A minor fix of the number of params
> fix number of parameters in RESULTS.md

- egs/librispeech/ASR/pruned_transducer_stateless/decode.py
- egs/librispeech/ASR/pruned_transducer_stateless2/decode.py
- egs/librispeech/ASR/pruned_transducer_stateless3/decode.py
- egs/librispeech/ASR/pruned_transducer_stateless4/decode.py
- egs/librispeech/ASR/pruned_transducer_stateless5/decode.py
Fix the error introduced by #622
> Fix fast_beam_search_LG log file name

- .github/workflows/style_check.yml
- egs/librispeech/ASR/local/compute_fbank_librispeech.py
- egs/librispeech/ASR/local/filter_cuts.py
- egs/librispeech/ASR/lstm_transducer_stateless/train.py
- egs/librispeech/ASR/lstm_transducer_stateless2/train.py
- egs/librispeech/ASR/lstm_transducer_stateless3/train.py
- egs/librispeech/ASR/pruned_stateless_emformer_rnnt2/train.py
- egs/librispeech/ASR/pruned_transducer_stateless/train.py
- egs/librispeech/ASR/pruned_transducer_stateless2/train.py
- egs/librispeech/ASR/pruned_transducer_stateless3/train.py
- egs/librispeech/ASR/pruned_transducer_stateless4/train.py
- egs/librispeech/ASR/pruned_transducer_stateless5/train.py
- egs/librispeech/ASR/pruned_transducer_stateless6/train.py
Also, print warnings when an utterance is filtered out.
See also
- https://github.com/k2-fsa/icefall/issues/603#issuecomment-1270203039
- https://github.com/k2-fsa/icefall/issues/603#issuecomment-1270491321
@ngoel17
Could you try this PR?
> Filter utterances with number_tokens > number_feature_frames.

- docker/Ubuntu18.04-pytorch1.12.1-cuda11.3-cudnn8/Dockerfile
Installing kaldifeat inside the docker.
> add kaldifeat

- egs/librispeech/ASR/conformer_ctc2/train.py
- egs/librispeech/ASR/conformer_ctc2/transformer.py
- egs/librispeech/ASR/local/compile_hlg.py
- egs/tedlium3/ASR/transducer_stateless/asr_datamodule.py
- icefall/decode.py
- icefall/utils.py
This is a small refactoring before the tedlium3 `conformer_ctc2` recipe. Also, extend `1best` decoding with LM weights scales.
> Small code refactoring

- egs/aidatatang_200zh/ASR/prepare.sh
- egs/aishell/ASR/prepare.sh
- egs/aishell2/ASR/prepare.sh
- egs/aishell4/ASR/prepare.sh
- egs/alimeeting/ASR/prepare.sh
- egs/csj/ASR/prepare.sh
- egs/gigaspeech/ASR/prepare.sh
- egs/librispeech/ASR/prepare.sh
- egs/ptb/LM/prepare.sh
- egs/spgispeech/ASR/prepare.sh
- egs/tal_csasr/ASR/prepare.sh
- egs/tedlium3/ASR/prepare.sh
- egs/timit/ASR/prepare.sh
- egs/wenetspeech/ASR/prepare.sh
- egs/yesno/ASR/prepare.sh
This PR fix the segmentation fault reported in #674
> Fix segmentation fault

- egs/librispeech/ASR/RESULTS.md
See <https://github.com/k2-fsa/icefall/pull/675> for more details.
> update multidataset zipformer results

- egs/librispeech/ASR/pruned_transducer_stateless7/zipformer.py
remove the duplicate line of Zipformer.py
> remove the duplicate line of Zipformer.py

- egs/librispeech/ASR/transducer_lstm/train.py
Fix transducer lstm egs bug as mentioned in issue 579
> Update train.py 

- egs/librispeech/ASR/pruned_transducer_stateless7_ctc_bs/frame_reducer.py
> Optimize frame_reducer.py

- docs/source/model-export/export-with-torch-jit-script.rst
- docs/source/recipes/Non-streaming-ASR/aishell/conformer_ctc.rst
- docs/source/recipes/Non-streaming-ASR/librispeech/conformer_ctc.rst
- docs/source/recipes/Non-streaming-ASR/librispeech/index.rst
- docs/source/recipes/Non-streaming-ASR/librispeech/pruned_transducer_stateless.rst
- docs/source/recipes/Non-streaming-ASR/librispeech/zipformer_ctc_blankskip.rst
- docs/source/recipes/Non-streaming-ASR/librispeech/zipformer_mmi.rst
Add zipformer_ctc_blankskip.rst
> Add zipformer_ctc_blankskip.rst

- egs/librispeech/ASR/local/compile_hlg_using_openfst.py
- egs/tedlium3/ASR/conformer_ctc2/decode.py
- icefall/dist.py
This is to address https://github.com/k2-fsa/icefall/issues/800 + several small fixes.
> Not removing result_dir in tedlium3 conformer ctc2

- .github/scripts/run-librispeech-pruned-transducer-stateless7-2022-11-11.sh
- .github/workflows/run-librispeech-2022-11-11-stateless7.yml
- egs/librispeech/ASR/pruned_transducer_stateless7/export.py
- egs/librispeech/ASR/pruned_transducer_stateless7/onnx_check.py
- egs/librispeech/ASR/pruned_transducer_stateless7/onnx_pretrained.py
- egs/librispeech/ASR/pruned_transducer_stateless7/scaling.py
- egs/librispeech/ASR/pruned_transducer_stateless7/test_onnx.py
- egs/librispeech/ASR/pruned_transducer_stateless7/zipformer.py
- Adding onnx support to pruned_transducer_stateless7 export.py
- Adding torch.onnx.is_in_onnx_export to unsupported operations
- Adding torch pretrained script
- Adding onnx test
> Add Zipformer Onnx Support

- icefall/dist.py
See https://github.com/k2-fsa/icefall/commit/2fd970b6821d47dacb2e6513321520db21fff67b#r94977557
and
https://github.com/k2-fsa/icefall/commit/2fd970b6821d47dacb2e6513321520db21fff67b#commitcomment-94885632
New arguments should be added to the end of the argument list for backward compatibility.
> Fix setup_dist

- egs/librispeech/ASR/conv_emformer_transducer_stateless2/emformer2.py
> fix init_states in conv emformer2

- egs/librispeech/ASR/pruned_transducer_stateless7/train.py
See https://github.com/k2-fsa/icefall/pull/843#issuecomment-1386454863
> hardcode --filter-uneven-sized-batch

- egs/aishell/ASR/README.md
- egs/librispeech/ASR/README.md
- egs/timit/ASR/README.md
- egs/yesno/ASR/README.md
edit README in egs/{aishell,librispeech,timit,yesno}/ASR
> fix expired links

- egs/librispeech/ASR/pruned_transducer_stateless7/train.py
- egs/librispeech/ASR/pruned_transducer_stateless7_ctc/train.py
- egs/librispeech/ASR/pruned_transducer_stateless7_ctc_bs/train.py
- egs/librispeech/ASR/pruned_transducer_stateless7_streaming/train.py
- egs/librispeech/ASR/pruned_transducer_stateless8/train.py
- egs/librispeech/ASR/streaming_conformer_ctc/train.py
See https://github.com/k2-fsa/icefall/pull/574
> shuffle full Librispeech for zipformer recipes

- egs/librispeech/ASR/pruned_transducer_stateless7/generate_averaged_model.py
Generate the averaged model from exp-dir.
Usage:
(1) use the checkpoint exp_dir/epoch-iter.pt
./pruned_transducer_stateless7/generate_averaged_model.py \
--epoch 28 \
--avg 15 \
--exp-dir ./pruned_transducer_stateless7/exp
(2) use the checkpoint exp_dir/checkpoint-iter.pt
./pruned_transducer_stateless7/generate_averaged_model.py \
--iter 22000 \
--avg 5 \
--exp-dir ./pruned_transducer_stateless7/exp
> Add generate_averaged_model.py

- icefall/mmi_graph_compiler.py
Fix one mmi graph compiler issue.
> fix mmi graph compiler bug.

- egs/librispeech/ASR/RESULTS.md
Ref: https://github.com/k2-fsa/icefall/pull/745#issuecomment-1427222290
> Add small streaming Zipformer transducer model

- egs/librispeech/ASR/transducer/test_rnn.py
- icefall/utils.py
Reference: https://github.com/wenet-e2e/wenet/blob/main/wenet/utils/mask.py#L195
> Modify make_pad_mask to support TensorRT

- egs/aishell/ASR/local/prepare_char_lm_training_data.py
- egs/aishell/ASR/prepare.sh
Add prepare_char_lm_training_data.py in local/ for char-based lm train data preparation process.
Add steps 9,10,11 in prepare.sh for lm data preparation and RNN lm training.
https://github.com/k2-fsa/icefall/issues/920
> Add char-based language model training process for aishell.

- egs/gigaspeech/ASR/local/generate_unique_lexicon.py
Aim to support phone-based model.
> Add UniqueLexicon for gigaspeech

- egs/gigaspeech/ASR/pruned_transducer_stateless2/decode.py
- egs/gigaspeech/ASR/pruned_transducer_stateless2/train.py
1. Add support for use-averaged-model
2. Change start-epoch from 0 to 1
3. Fix some typo
> Add averaged model && change start from 0 to 1 && fix typo for gigaspeech

- icefall/rnn_lm/export-onnx.py
used by https://github.com/k2-fsa/sherpa-onnx/pull/133
> add meta-data embedding_dim to RNNLM onnx-model

- egs/librispeech/ASR/local/compile_hlg.py
- egs/librispeech/ASR/local/compile_lg.py
- egs/timit/ASR/local/compile_hlg.py
- egs/yesno/ASR/local/compile_hlg.py
Someone is trying the TIMIT recipe and gets the following error
The error is introduced by https://github.com/k2-fsa/k2/pull/1140
This PR fixes the error.
> fix compiling HLG

- egs/librispeech/ASR/local/download_lm.py
> Fix broken code in download_lm.py

- egs/librispeech/ASR/pruned_transducer_stateless5/export-onnx-streaming.py
- egs/librispeech/ASR/pruned_transducer_stateless5/onnx_pretrained-streaming.py
An exported streaming conformer model from https://github.com/k2-fsa/icefall/pull/454
can be found at
https://huggingface.co/csukuangfj/sherpa-onnx-streaming-conformer-en-2023-05-09
---
See also https://github.com/k2-fsa/sherpa-onnx/issues/132
@jingzhaoou
> Support exporting streaming conformer to ONNX

- icefall/rnn_lm/train.py
> fix rnn_lm/train.py usage

- docs/source/installation/index.rst
As discussed in [k2-fsa/icefall#1056](https://github.com/k2-fsa/icefall/issues/1056)
Note some logs including hostname, ip and local paths are anonymized.
> Update the yesno recipe logs in doc

- egs/librispeech/ASR/pruned_transducer_stateless7_streaming/ncnn_custom_layer.py
- egs/librispeech/ASR/pruned_transducer_stateless7_streaming/streaming-ncnn-decode.py
- egs/librispeech/ASR/pruned_transducer_stateless7_streaming/zipformer2.py
We won't maintain our modified ncnn any longer.
> Support using the latest master from tencent/ncnn

- egs/librispeech/ASR/pruned_transducer_stateless7/finetune.py
- egs/librispeech/ASR/pruned_transducer_stateless7/train.py
- icefall/utils.py
> Fix stateless7 training error

- egs/wenetspeech/ASR/pruned_transducer_stateless5/export-onnx-streaming.py
- egs/wenetspeech/ASR/pruned_transducer_stateless5/export-onnx.py
- egs/wenetspeech/ASR/pruned_transducer_stateless5/onnx_check.py
- egs/wenetspeech/ASR/pruned_transducer_stateless5/onnx_pretrained-streaming.py
- egs/wenetspeech/ASR/pruned_transducer_stateless5/onnx_pretrained.py
Two exported models can be found at
- https://huggingface.co/csukuangfj/sherpa-onnx-streaming-conformer-zh-2023-05-23
- https://huggingface.co/csukuangfj/sherpa-onnx-conformer-zh-2023-05-23
You can use them in https://github.com/k2-fsa/sherpa-onnx
> Add onnx export scripts for wenetspeech recipe.

- egs/librispeech/ASR/transducer/train.py
- egs/librispeech/ASR/transducer_stateless/train.py
- egs/librispeech/ASR/transducer_stateless2/train.py
> remove outdated code in train.py

- icefall/diagnostics.py
update diagnostics, print limits in Balancer, merge changes from Dan's branch zlm59
> update diagnostics, print limits in Balancer, 

- egs/librispeech/ASR/zipformer/export-onnx-streaming.py
- egs/librispeech/ASR/zipformer/export-onnx.py
- egs/librispeech/ASR/zipformer/model.py
- egs/librispeech/ASR/zipformer/onnx_pretrained-streaming.py
- egs/librispeech/ASR/zipformer/onnx_pretrained.py
- egs/librispeech/ASR/zipformer/scaling.py
- egs/librispeech/ASR/zipformer/scaling_converter.py
- egs/librispeech/ASR/zipformer/subsampling.py
- egs/librispeech/ASR/zipformer/zipformer.py
> add updated zipformer onnx export

- egs/librispeech/ASR/pruned_transducer_stateless2/beam_search.py
- egs/tedlium3/ASR/RESULTS.md
- egs/tedlium3/ASR/zipformer/asr_datamodule.py
- egs/tedlium3/ASR/zipformer/beam_search.py
- egs/tedlium3/ASR/zipformer/decode.py
- egs/tedlium3/ASR/zipformer/decoder.py
- egs/tedlium3/ASR/zipformer/encoder_interface.py
- egs/tedlium3/ASR/zipformer/export.py
- egs/tedlium3/ASR/zipformer/joiner.py
- egs/tedlium3/ASR/zipformer/model.py
- egs/tedlium3/ASR/zipformer/optim.py
- egs/tedlium3/ASR/zipformer/pretrained.py
- egs/tedlium3/ASR/zipformer/profile.py
- egs/tedlium3/ASR/zipformer/scaling.py
- egs/tedlium3/ASR/zipformer/scaling_converter.py
- egs/tedlium3/ASR/zipformer/subsampling.py
- egs/tedlium3/ASR/zipformer/train.py
- egs/tedlium3/ASR/zipformer/zipformer.py
This is a TedLium recipe for the new zipformer model. I am still tuning the training recipe so this is WIP.
> Zipformer for TedLium

- icefall/rnn_lm/train.py
If epochs are long, it is helpful to start from batch just like other trainings
> Add start-batch option for RNNLM training

- egs/wenetspeech/ASR/local/prepare_char_lm_training_data.py
- egs/wenetspeech/ASR/local/sort_lm_training_data.py
Add two symlinks for Wenetspeech LM training.
> Fix missing symlinks for wenetspeech recipe

- docs/source/conf.py
- docs/source/installation/index.rst
Point users to install k2 with pre-compiled wheels using `pip install`.
> Update installation doc.

- docs/source/decoding-with-langugage-models/LODR.rst
- docs/source/decoding-with-langugage-models/rescoring.rst
- docs/source/decoding-with-langugage-models/shallow-fusion.rst
- egs/librispeech/ASR/RESULTS.md
- egs/librispeech/ASR/pruned_transducer_stateless7_streaming/decode.py
- egs/librispeech/ASR/zipformer/decode.py
This PR support decoding with an external language model in the zipformer recipe.
The detailed results will be updated afterwards.
> Decode zipformer with external LMs

- docs/source/model-export/export-model-state-dict.rst
- docs/source/model-export/export-ncnn-conv-emformer.rst
- docs/source/model-export/export-ncnn-lstm.rst
- docs/source/model-export/export-ncnn-zipformer.rst
- docs/source/model-export/export-onnx.rst
- docs/source/model-export/export-with-torch-jit-script.rst
- docs/source/model-export/export-with-torch-jit-trace.rst
> Updated docs 

- egs/librispeech/ASR/pruned_transducer_stateless2/beam_search.py
This PR follows the discussion in https://github.com/k2-fsa/icefall/issues/1206
> Update padding modified beam search

- docs/source/conf.py
- docs/source/for-dummies/data-preparation.rst
- docs/source/for-dummies/decoding.rst
- docs/source/for-dummies/environment-setup.rst
- docs/source/for-dummies/index.rst
- docs/source/for-dummies/model-export.rst
- docs/source/for-dummies/training.rst
- docs/source/index.rst
- egs/yesno/ASR/tdnn/onnx_pretrained.py
> WIP: Add icefall tutorials for dummies.

- egs/aishell/ASR/pruned_transducer_stateless7/export-onnx.py
- egs/commonvoice/ASR/pruned_transducer_stateless7/export-onnx.py
- egs/librispeech/ASR/conv_emformer_transducer_stateless2/export-onnx.py
- egs/librispeech/ASR/lstm_transducer_stateless2/export-onnx-zh.py
- egs/librispeech/ASR/lstm_transducer_stateless2/export-onnx.py
- egs/librispeech/ASR/pruned_transducer_stateless/export-onnx.py
- egs/librispeech/ASR/pruned_transducer_stateless3/export-onnx.py
- egs/librispeech/ASR/pruned_transducer_stateless5/export-onnx-streaming.py
- egs/librispeech/ASR/pruned_transducer_stateless5/export-onnx.py
- egs/librispeech/ASR/pruned_transducer_stateless7/export-onnx.py
- egs/librispeech/ASR/pruned_transducer_stateless7_streaming/export-onnx-zh.py
- egs/librispeech/ASR/pruned_transducer_stateless7_streaming/export-onnx.py
- egs/librispeech/ASR/zipformer/export-onnx-streaming.py
- egs/librispeech/ASR/zipformer/export-onnx.py
- egs/wenetspeech/ASR/pruned_transducer_stateless2/export-onnx.py
- egs/wenetspeech/ASR/pruned_transducer_stateless5/export-onnx-streaming.py
- egs/wenetspeech/ASR/pruned_transducer_stateless5/export-onnx.py
Please see also https://github.com/k2-fsa/sherpa-onnx/issues/327
> Fix exporting decoder model to onnx

- docs/source/recipes/Non-streaming-ASR/librispeech/distillation.rst
- egs/librispeech/ASR/distillation_with_hubert.sh
> Fix docs for MVQ

- egs/aishell/ASR/tdnn_lstm_ctc/asr_datamodule.py
See [CutMix](https://github.com/lhotse-speech/lhotse/blob/5c617ee800376418c9c40acbf24db70540882266/lhotse/dataset/cut_transforms/mix.py#L14C13-L14C13) for more details.
> Compatible with new lhotse versions.

- egs/aishell/ASR/prepare.sh
- egs/librispeech/ASR/prepare.sh
> fixes for data preparation

- egs/aidatatang_200zh/ASR/pruned_transducer_stateless2/asr_datamodule.py
- egs/aishell/ASR/transducer_stateless_modified-2/asr_datamodule.py
- egs/aishell2/ASR/pruned_transducer_stateless5/asr_datamodule.py
- egs/aishell4/ASR/pruned_transducer_stateless5/asr_datamodule.py
- egs/alimeeting/ASR/pruned_transducer_stateless2/asr_datamodule.py
- egs/alimeeting/ASR_v2/pruned_transducer_stateless7/asr_datamodule.py
- egs/ami/ASR/pruned_transducer_stateless7/asr_datamodule.py
- egs/ami/SURT/dprnn_zipformer/asr_datamodule.py
- egs/commonvoice/ASR/pruned_transducer_stateless7/asr_datamodule.py
- egs/csj/ASR/local/utils/asr_datamodule.py
- egs/gigaspeech/ASR/conformer_ctc/asr_datamodule.py
- egs/gigaspeech/ASR/pruned_transducer_stateless2/asr_datamodule.py
- egs/libricss/SURT/dprnn_zipformer/asr_datamodule.py
- egs/librispeech/ASR/pruned2_knowledge/asr_datamodule.py
- egs/librispeech/ASR/pruned_transducer_stateless3/asr_datamodule.py
- egs/librispeech/ASR/pruned_transducer_stateless7/gigaspeech.py
- egs/librispeech/ASR/tdnn_lstm_ctc/asr_datamodule.py
- egs/mgb2/ASR/conformer_ctc/asr_datamodule.py
- egs/multi_zh-hans/ASR/zipformer/asr_datamodule.py
- egs/spgispeech/ASR/pruned_transducer_stateless2/asr_datamodule.py
- egs/swbd/ASR/conformer_ctc/asr_datamodule.py
- egs/tal_csasr/ASR/pruned_transducer_stateless5/asr_datamodule.py
- egs/tedlium3/ASR/transducer_stateless/asr_datamodule.py
- egs/timit/ASR/tdnn_lstm_ctc/asr_datamodule.py
- egs/wenetspeech/ASR/pruned_transducer_stateless2/asr_datamodule.py
- egs/xbmu_amdo31/ASR/pruned_transducer_stateless5/asr_datamodule.py
Refer to https://github.com/k2-fsa/icefall/pull/1249#issuecomment-1766345149 for more details.
> Fixed compatibility with the latest Lhotse

- egs/librispeech/ASR/zipformer/zipformer.py
Following : 
- https://github.com/k2-fsa/icefall/pull/1131
- https://github.com/k2-fsa/sherpa/issues/490#issuecomment-1767360266
Replace all ```.chunk(..., dim=-1)``` to avoid issue in sherpa (gpu)
> Fix chunk issue for sherpa

- docs/source/contributing/code-style.rst
> Fix typo in code-style.rst

- egs/librispeech/ASR/pruned_transducer_stateless7/model.py
- icefall/utils.py
- add extra check of 'x' and 'x_lens' to earlier point in Transducer model
- specify 'utf' encoding when opening text files for writing (recogs, errs)
> small enhancements

- requirements-ci.txt
- Replace https://k2-fsa.org/nightly/ with https://k2-fsa.github.io/k2/cpu.html
- Update k2 to the latest version
> Fix CI tests

- docs/source/recipes/Non-streaming-ASR/aishell/conformer_ctc.rst
- docs/source/recipes/Non-streaming-ASR/aishell/tdnn_lstm_ctc.rst
- docs/source/recipes/Non-streaming-ASR/librispeech/pruned_transducer_stateless.rst
- docs/source/recipes/RNN-LM/librispeech/lm-training.rst
intalled --> installed
Basicly --> Basically
langugage --> language
> fix more typos

- egs/tedlium3/ASR/zipformer/decode.py
- egs/tedlium3/ASR/zipformer/train.py
ref: https://github.com/k2-fsa/icefall/issues/1339
> fix an `ImportError` in the tedlium3/zipformer recipe

- egs/aishell/ASR/zipformer/train.py
- egs/gigaspeech/ASR/zipformer/asr_datamodule.py
- egs/gigaspeech/ASR/zipformer/train.py
- egs/libriheavy/ASR/zipformer_prompt_asr/optim.py
- egs/libriheavy/ASR/zipformer_prompt_asr/train_baseline.py
- egs/libriheavy/ASR/zipformer_prompt_asr/train_bert_encoder.py
- egs/librispeech/ASR/tiny_transducer_ctc/asr_datamodule.py
- egs/librispeech/ASR/tiny_transducer_ctc/ctc_decode.py
- egs/librispeech/ASR/tiny_transducer_ctc/encoder.py
- egs/librispeech/ASR/tiny_transducer_ctc/export.py
- egs/librispeech/ASR/tiny_transducer_ctc/train.py
- egs/librispeech/ASR/zipformer_ctc/export.py
- egs/librispeech/ASR/zipformer_ctc/train.py
- icefall/diagnostics.py
PR https://github.com/k2-fsa/icefall/pull/848 and https://github.com/k2-fsa/icefall/pull/941
> Minor refinements for some stale but recently merged PRs

- egs/wenetspeech/ASR/prepare.sh
Update the parameter 'vocab-size'
> Update the parameter 'vocab-size'

- egs/librispeech/ASR/pruned_transducer_stateless2/export.py
- egs/librispeech/ASR/pruned_transducer_stateless2/lstmp.py
- egs/librispeech/ASR/pruned_transducer_stateless2/scaling_converter.py
> Fix torch.jit.script() export for pruned_transducer_stateless2

- .github/scripts/multi-zh-hans.sh
- .github/workflows/multi-zh-hans.yml
- egs/librispeech/ASR/zipformer/export-onnx-streaming.py
To keep the exported models always compatible with the latest code, we use GitHub CI to test the exported models and upload them to huggingface and github automagically.
> Use CI to check the exported model and upload models automagically

- .github/scripts/multi-zh-hans.sh
- .github/workflows/multi-zh-hans.yml
- egs/librispeech/ASR/zipformer/onnx_pretrained-streaming-ctc.py
- egs/librispeech/ASR/zipformer/onnx_pretrained-streaming.py
- egs/multi_zh-hans/ASR/zipformer/export-onnx-streaming-ctc.py
- egs/multi_zh-hans/ASR/zipformer/onnx_pretrained-streaming-ctc.py
Will add graph support with [kaldi-decoder](https://github.com/k2-fsa/kaldi-decoder) in a separate PR.
> Add greedy search for streaming zipformer CTC.

- egs/librispeech/ASR/zipformer/optim.py
Fix https://github.com/k2-fsa/icefall/issues/1473
> minor fix of zipformer/optim.py

- .github/workflows/build-docker-image.yml
- .github/workflows/run-docker-image.yml
- docker/torch1.12.1-cuda11.3.dockerfile
- docker/torch1.13.0-cuda11.6.dockerfile
- docker/torch1.9.0-cuda10.2.dockerfile
- docker/torch2.1.0-cuda11.8.dockerfile
- docker/torch2.1.0-cuda12.1.dockerfile
- docker/torch2.2.0-cuda11.8.dockerfile
- docker/torch2.2.0-cuda12.1.dockerfile
- docs/source/docker/intro.rst
please see
https://hub.docker.com/r/k2fsa/icefall/tags?page=1&name=2.2.0
> Provider docker images for torch 2.2.0

- egs/ljspeech/TTS/vits/README.md
- egs/ljspeech/TTS/vits/export-onnx.py
See also
https://github.com/k2-fsa/sherpa-onnx/pull/625
> Update export-onnx.py for vits to support sherpa-onnx.

- egs/librispeech/WSASR/conformer_ctc2/train.py
> fixed formatting issue of PR #1528

- egs/commonvoice/ASR/local/preprocess_commonvoice.py
ref: https://github.com/k2-fsa/icefall/issues/1531
> Support pl for the `commonvoice` recipe

- egs/aishell/ASR/whisper/train.py
- egs/commonvoice/ASR/pruned_transducer_stateless7_streaming/do_not_use_it_directly.py
- egs/commonvoice/ASR/pruned_transducer_stateless7_streaming/finetune.py
- egs/commonvoice/ASR/pruned_transducer_stateless7_streaming/train.py
- egs/multi_zh-hans/ASR/whisper/train.py
- egs/wenetspeech/ASR/whisper/train.py
- egs/wenetspeech/KWS/zipformer/train.py
akin to: https://github.com/k2-fsa/icefall/pull/1269
> fixes for init value of `diagnostics.TensorDiagnosticOptions`

- egs/librispeech/ASR/prepare_lm.sh
- egs/librispeech/ASR/prepare_mmi.sh
REF: https://github.com/k2-fsa/icefall/issues/1624
> Fix an error occured during mmi preparation 

- egs/librispeech/ASR/README.md
- egs/librispeech/ASR/RESULTS.md
Update RESULTS.md, adding results and model links of zipformer-small/medium CTC/AED models
> Update RESULTS.md about zipformer-small/medium CTC/AED models

- egs/gigaspeech/KWS/run.sh
- egs/wenetspeech/KWS/run.sh
KWS `run.sh` script writing bug
> "-" replace "_" fix writing bug

- .github/scripts/docker/generate_build_matrix.py
- .github/workflows/build-docker-image.yml
- .github/workflows/run-docker-image.yml
- docker/torch2.0.0-cuda11.7.dockerfile
- docker/torch2.1.0-cuda11.8.dockerfile
- docker/torch2.1.0-cuda12.1.dockerfile
- docker/torch2.2.0-cuda11.8.dockerfile
- docker/torch2.2.0-cuda12.1.dockerfile
- docker/torch2.2.1-cuda11.8.dockerfile
- docker/torch2.2.1-cuda12.1.dockerfile
- docker/torch2.2.2-cuda11.8.dockerfile
- docker/torch2.2.2-cuda12.1.dockerfile
- docker/torch2.3.1-cuda11.8.dockerfile
- docker/torch2.3.1-cuda12.1.dockerfile
- docker/torch2.4.0-cuda11.8.dockerfile
- docker/torch2.4.0-cuda12.1.dockerfile
- docker/torch2.4.0-cuda12.4.dockerfile
> Add docker images for torch 2.4

- egs/librispeech/ASR/zipformer/export-onnx.py
See https://github.com/k2-fsa/icefall/pull/670 for more details.
> fix triton onnx export

- egs/alimeeting/ASR_v2/pruned_transducer_stateless7/asr_datamodule.py
source: https://github.com/k2-fsa/icefall/issues/1742
> fixed wrong default value for the `alimeeting` recipe

- egs/alimeeting/ASR_v2/local/prepare_alimeeting_gss.sh
- egs/ami/ASR/local/prepare_ami_gss.sh
source: https://github.com/k2-fsa/icefall/issues/1738
> fixed gss scripts for `alimeeting` and `ami` recipes

- egs/libricss/SURT/dprnn_zipformer/pretrained.py
- egs/libricss/SURT/dprnn_zipformer/train.py
Fixes #1784 
CC @nightwatcher-of-abyss
> Add pretrained.py for SURT

- egs/xbmu_amdo31/ASR/pruned_transducer_stateless7/train.py
> fixed failed assertion in the `xbmu_ambo31` recipe

- egs/librispeech/ASR/zipformer/optim.py
From Dan: "This has simplifying refactoring, but I also just added a change to diagnostics for when grads are clipped, which should help diagnose problems with models. Anyone who has a model that is not converging well or which is getting percent-clipped > 0 should try that version of optim.py, which has more informative
error messages."
> Refactor optimizer

- egs/aishell/ASR/zipformer/train.py
- egs/aishell/ASR/zipformer/train_bbpe.py
> Fix aishell training

- egs/tedlium3/ASR/pruned_transducer_stateless/train.py
- egs/tedlium3/ASR/transducer_stateless/train.py
Fixes #1928 
CC @HajarMazaheri
> Fix convert_texts_into_ids() in the tedlium3 recipe.
