k2-fsa/icefall

README.md
egs/librispeech/ASR/README.md
egs/librispeech/ASR/conformer_ctc/train.py
egs/librispeech/ASR/conformer_ctc/transformer.py
egs/librispeech/ASR/tdnn_lstm_ctc/README.md
requirements.txt

Add doc about installation and usage

---

egs/librispeech/ASR/conformer_ctc/README.md
egs/librispeech/ASR/conformer_ctc/decode.py
egs/librispeech/ASR/conformer_ctc/pretrained.py
egs/librispeech/ASR/conformer_ctc/train.py
icefall/decode.py

nbest oracle WER can help us evaluate different n-best rescoring methods 
as it is the best WER that we could get if we had the perfect rescoring method.

Support computing nbest oracle WER.

---

README.md
egs/librispeech/ASR/conformer_ctc/README.md
egs/librispeech/ASR/conformer_ctc/pretrained.py

It demonstrates how to set up the environment to run pre-trained models.
[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/drive/1huyupXAcHsUrKaWfI83iMEJ6J0Nh0213?usp=sharing)
Due to limited memory provided by Colab, it is only able to run HLG decoding with Colab.
You have to upgrade to Colab Pro to run `LM rescoring` with Colab.

Add a link to Colab.

---

.github/workflows/run-yesno-recipe.yml
README.md
egs/librispeech/ASR/local/compute_fbank_librispeech.py
egs/librispeech/ASR/local/compute_fbank_musan.py
egs/librispeech/ASR/tdnn_lstm_ctc/asr_datamodule.py
egs/librispeech/ASR/tdnn_lstm_ctc/decode.py
egs/yesno/ASR/README.md
egs/yesno/ASR/local/compile_hlg.py
egs/yesno/ASR/local/compute_fbank_yesno.py
egs/yesno/ASR/local/prepare_lang.py
egs/yesno/ASR/prepare.sh
egs/yesno/ASR/shared
egs/yesno/ASR/tdnn/asr_datamodule.py
egs/yesno/ASR/tdnn/decode.py
egs/yesno/ASR/tdnn/model.py
egs/yesno/ASR/tdnn/train.py
icefall/dataset/datamodule.py

There are 60 sound files in the dataset. 30 sound files are used for training and the other 30 files are used for testing.
The decoding log is below:
```
$ ./tdnn/decode.py --epoch 49
2021-08-21 17:20:27,047 INFO [decode.py:321] Decoding started
2021-08-21 17:20:27,047 INFO [decode.py:322] {'exp_dir': PosixPath('tdnn/exp'), 'lang_dir': PosixPath('data/lang_phone'), 'lm_dir': PosixPath('data/lm'), 'feature_dim': 23, 'subsampling_factor': 1, 'search_beam': 20, 'output_beam': 5, 'min_active_states': 30, 'max_active_states': 10000, 'use_double_scores': True, 'method': '1best', 'num_paths': 30, 'epoch': 49, 'avg': 15, 'feature_dir': PosixPath('data/fbank'), 'max_duration': 30.0, 'bucketing_sampler': False, 'num_buckets': 10, 'concatenate_cuts': False, 'duration_factor': 1.0, 'gap': 1.0, …
```

Add recipe for the yes_no dataset.

---

docs/source/recipes/librispeech/conformer_ctc.rst
egs/librispeech/ASR/RESULTS.md
egs/librispeech/ASR/conformer_ctc/decode.py
egs/librispeech/ASR/conformer_ctc/pretrained.py
egs/librispeech/ASR/tdnn_lstm_ctc/decode.py
egs/librispeech/ASR/tdnn_lstm_ctc/pretrained.py
egs/yesno/ASR/tdnn/decode.py
egs/yesno/ASR/tdnn/pretrained.py
icefall/decode.py
test/test_decode.py

Usage:
```bash
epoch=25
avg=1
./conformer_ctc/decode.py \
--epoch $epoch \
--avg $avg \
--max-duration 300 \
--bucketing-sampler 0 \
--full-libri 0 \
--exp-dir conformer_ctc/exp \
--lang-dir data/lang_bpe_500 \
--method ctc-decoding
```
Decoding log:
```
2021-09-26 12:44:31,033 INFO [decode.py:537] Decoding started
2021-09-26 12:44:31,033 INFO [decode.py:538] 
{'lm_dir': PosixPath('data/lm'), 'subsampling_factor': 4, 'vgg_frontend': False, 'use_feat_batchnorm': True, 
'feature_dim': 80, 'nhead': 8, 'attention_dim': 512, 'num_decoder_layers': 6, 'search_beam': 20, 'output_beam': 8,
'min_active_states': 30, 'max_active_states': 10000, 'use_double_scores': True, 
'epoch': 25, 'avg': 1, 'method': 'ctc-decoding', 'num_paths': 100, 'nbest_scale': 0.5, 
'export': False, 'exp_dir': …
```

Support pure ctc decoding requiring neither a lexicon nor an n-gram LM

---

docs/source/recipes/librispeech/conformer_ctc.rst

This PR is a response for #59. 
I mainly modify the decoding part in conformer_ctc.rst and add 'ctc-decoding' to the decoding part.
I wonder if it is necessary to modify the pretrained.py to support ctc decoding and make tdnn_lstm_ctc to support ctc decoding. If do this, it seems many changes are needed.

Update the documentation to include "ctc-decoding"

---

egs/librispeech/ASR/tdnn_lstm_ctc/asr_datamodule.py
egs/yesno/ASR/tdnn/asr_datamodule.py

As mentioned in #71 -- I simply hardcoded BucketingSampler in place of SingleCutSampler as I don't see a reason not to use it.
Edit: I checked that it works just on yesno.

Use BucketingSampler for dev and test data

---

icefall/decode.py

Closes #105
It becomes slightly faster after this fix.
With this PR,
- test-clean: 11 minutes
- test-other: 11 minutes
Before this PR
- test-clean: 14 minutes
- test-other: 13 minutes
Here are some decoding logs with and without this PR.
```
2021-11-05 20:46:37,389 INFO [decode.py:656] Number of model parameters: 109226120
2021-11-05 20:46:38,633 INFO [decode.py:476] batch 0/?, cuts processed until now is 6
/ceph-fj/fangjun/open-source-2/lhotse-bpe-500/lhotse/dataset/sampling/single_cut.py:237: UserWarning: The first cut drawn in batch co
llection violates the max_frames, max_cuts, or max_duration constraints - we'll return it anyway. Consider increasing max_frames/max_
cuts/max_duration.
warnings.warn(
2021-11-05 20:47:52,494 INFO [decode.py:476] batch 100/?, cuts processed until now is …
```

Remove duplicated token seq in rescoring.

---

icefall/decode.py

It does not affect the WER since `Nbest.fsa.scores` is not used after invoking `Nbest.compute_am_scores()`, but the implementation is incorrect. This PR fixes that.

Fix a bug in Nbest.compute_am_scores and Nbest.compute_lm_scores.

---

README.md
docs/source/recipes/librispeech/conformer_ctc.rst
egs/librispeech/ASR/RESULTS.md
egs/librispeech/ASR/conformer_ctc/ali.py
egs/librispeech/ASR/conformer_ctc/decode.py
egs/librispeech/ASR/conformer_ctc/export.py
egs/librispeech/ASR/conformer_ctc/pretrained.py
egs/librispeech/ASR/conformer_ctc/train.py
egs/librispeech/ASR/conformer_ctc/transformer.py
icefall/decode.py

The best WERs for the librispeech test datasets are
|     | test-clean | test-other |
|-----|------------|------------|
| WER | 2.42       | 5.73       |
| ngram_lm_scale | attention_scale |
|----------------|-----------------|
| 2.0            | 2.0             |
using HLG decoding + n-gram LM rescoring + attention decoder rescoring.
---
Note  that
- vocab size is changed from 5000 to 500
- att rate is changed from 0.7 to 0.8
- The best WER occurs at `epoch-77.pt`, with `--avg=55`.

Update result for the librispeech recipe using vocab size 500 and att rate 0.8

---

icefall/decode.py

The fix is proposed by @danpovey

Handle empty lattices in attention decoder rescoring.

---

egs/librispeech/ASR/conformer_ctc/decode.py
egs/librispeech/ASR/conformer_mmi/decode.py
egs/librispeech/ASR/local/compile_hlg.py
egs/librispeech/ASR/tdnn_lstm_ctc/decode.py
egs/yesno/ASR/local/compile_hlg.py

See https://github.com/k2-fsa/k2/issues/874
Note: It is not a problem in icefall since we don't use the `properties` attribute after changing its `labels` in-place.

Set fsa.properties to None after changing its labels in-place.

---

egs/librispeech/ASR/streaming_conformer_ctc/README.md
egs/librispeech/ASR/streaming_conformer_ctc/asr_datamodule.py
egs/librispeech/ASR/streaming_conformer_ctc/conformer.py
egs/librispeech/ASR/streaming_conformer_ctc/label_smoothing.py
egs/librispeech/ASR/streaming_conformer_ctc/streaming_decode.py
egs/librispeech/ASR/streaming_conformer_ctc/subsampling.py
egs/librispeech/ASR/streaming_conformer_ctc/train.py
egs/librispeech/ASR/streaming_conformer_ctc/transformer.py

Question: [With this modification](https://github.com/glynpu/icefall/blob/a333798a4ff98d7ad3d90a6f5faf9ee50e7d290a/egs/librispeech/ASR/conformer_ctc/conformer.py#L165) about mask, is the model really a streming model? The wer seems lower than expected. 
```
mask = ~subsequent_chunk_mask(
size=x.size(0), chunk_size=chunk_size, device=x.device
)
x = self.encoder(
x, pos_emb, mask=mask, src_key_padding_mask=src_key_padding_mask
)  # (T, B, F)
```
TODO List:
1. implement chunk_by_chunk decoding.
2. release training related code(or maybe another pr if this one only focus on decoding part).
Training is still in progress, following results is obtained with command:
```
./conformer_ctc/streaming_decode.py --epoch 29 --avg 6 --chunk_size 8
./conformer_ctc/streaming_decode.py --epoch 29 --avg 6 …
```

Draft streaming decoding

---

egs/librispeech/ASR/conformer_ctc/decode.py

Should be `G.dummy = 1`, not `G["dummy"] = 1`.
I was meaning `G.as_dict()["dummy"] = 1`.

Fix an error introduced while supporting torchscript.

---

.gitignore
egs/yesno/ASR/transducer/asr_datamodule.py
egs/yesno/ASR/transducer/beam_search.py
egs/yesno/ASR/transducer/decode.py
egs/yesno/ASR/transducer/decoder.py
egs/yesno/ASR/transducer/encoder.py
egs/yesno/ASR/transducer/joiner.py
egs/yesno/ASR/transducer/jointer.py
egs/yesno/ASR/transducer/model.py
egs/yesno/ASR/transducer/test_decoder.py
egs/yesno/ASR/transducer/test_encoder.py
egs/yesno/ASR/transducer/test_joiner.py
egs/yesno/ASR/transducer/test_jointer.py
egs/yesno/ASR/transducer/test_transducer.py
egs/yesno/ASR/transducer/train.py
icefall/utils.py
test/test_utils.py

```bash
$ ./transducer/decode.py
2021-12-06 16:50:33,363 INFO [asr_datamodule.py:218] About to get test cuts
2021-12-06 16:50:33,363 INFO [asr_datamodule.py:248] About to get test cuts
2021-12-06 16:50:33,956 INFO [decode.py:188] batch 0/?, cuts processed until now is 3
2021-12-06 16:50:36,368 INFO [decode.py:226] The transcripts are stored in transducer/exp-3/recogs-test_set.txt
2021-12-06 16:50:36,369 INFO [utils.py:387] [test_set] %WER 32.92% [79 / 240, 5 ins, 37 del, 37 sub ]
2021-12-06 16:50:36,370 INFO [decode.py:234] Wrote detailed error stats to transducer/exp-3/errs-test_set.txt
2021-12-06 16:50:36,371 INFO [decode.py:306] Done!
```
A very simple RNN-T training pipeline for the yesno dataset.  It uses greedy beam search for decoding.
Useful for the librispeech dataset.

RNN-T training for yesno.

---

egs/librispeech/ASR/conformer_ctc/conformer.py
egs/librispeech/ASR/conformer_ctc/train.py
egs/librispeech/ASR/conformer_ctc/transformer.py

This pull request try to remove all the batch norm in our model,  we replace the batch normalization for features with a scaling (with a scale value 0.1), and we remove the batch normalization in `ConvolutionModule`.  The experiment result shows below:
| Setting | test-clean | test-other |
| -------|  ----| ---- |
| baseline (latest icefall model) | 2.42 | 5.73|
| replace feat_batchnorm with 0.1 scale and remove batchnorm in Convmodule| 2.47 | 5.62|
The default setting remains unchanged for backward compatibility，you can try this change by modifying `feat_batchnorm` to 0.1 in conformer_ctc/train.py

Remove batchnorm

---

egs/librispeech/ASR/transducer/beam_search.py
egs/librispeech/ASR/transducer_lstm/beam_search.py
egs/librispeech/ASR/transducer_stateless/beam_search.py
egs/librispeech/ASR/transducer_stateless/conformer.py
egs/librispeech/ASR/transducer_stateless/decode.py
egs/librispeech/ASR/transducer_stateless/model.py
egs/librispeech/ASR/transducer_stateless/transformer.py

Fix the issue mentioned in https://github.com/k2-fsa/icefall/pull/143#discussion_r771528553
For a model trained using
```
./transducer_stateless/train.py \
--world-size 1 \
--num-epochs 20 \
--start-epoch 0 \
--exp-dir transducer_stateless/exp \
--full-libri 0 \
--max-duration 250 \
--lr-factor 3
```
When it is decoded with
```
./transducer_stateless/decode.py --epoch 5 --avg 3 --exp-dir ./transducer_stateless/exp --max-duration 100
```
The decoding log is
```
2021-12-18 09:58:43,173 INFO [decode.py:316] batch 0/?, cuts processed until now is 20
2021-12-18 09:59:41,255 INFO [decode.py:316] batch 100/?, cuts processed until now is 1406
2021-12-18 10:00:37,971 INFO [decode.py:316] batch 200/?, cuts processed until now is 2563
2021-12-18 10:00:43,287 INFO [decode.py:333] The transcripts are …
```

Limit the number of symbols per frame in RNN-T decoding.

---

egs/librispeech/ASR/transducer_stateless/beam_search.py
egs/librispeech/ASR/transducer_stateless/decode.py
egs/librispeech/ASR/transducer_stateless/pretrained.py

Some results when changing `--max-sym-per-frame`
You can see that when its value is >=2, the WERs for the LibriSpeech test datasets will not change.
```
./transducer_stateless/decode.py --epoch 20 --avg 10 --exp-dir ./transducer_stateless/exp-full --max-sym-per-frame 0 --max-duration 100
[test-clean-greedy_search] %WER 100.00% [52576 / 52576, 0 ins, 52576 del, 0 sub ]
[test-other-greedy_search] %WER 100.00% [52343 / 52343, 0 ins, 52343 del, 0 sub ]
```
```
./transducer_stateless/decode.py --epoch 20 --avg 10 --exp-dir ./transducer_stateless/exp-full --max-sym-per-frame 1 --max-duration 100
[test-clean-greedy_search] %WER 3.01% [1583 / 52576, 161 ins, 136 del, 1286 sub ]
[test-other-greedy_search] %WER 7.58% [3966 / 52343, 422 ins, 368 del, 3176 sub ]
```
It has few substitution errors …

Minor fix to maximum number of symbols per frame for RNN-T decoding.

---

egs/librispeech/ASR/RESULTS.md

The SHA1 is not available until the PR gets merged. So a separate PR is used to fill that information.

Add git sha1 to RESULTS.md for conformer encoder + stateless decoder.

---

README.md
egs/librispeech/ASR/RESULTS.md
egs/librispeech/ASR/transducer_stateless/beam_search.py

As we are using a stateless decoder, the output of the decoder depends only on 
the current input, so we can use the current input as a key to the cache to improve the hit rate
and reduce computation.
After continuing training for more epochs from https://github.com/k2-fsa/icefall/pull/162, we can get a lower WER on both test-clean and test-other.
|                           | test-clean | test-other | comment                                  |
|---------------------------|------------|------------|------------------------------------------|
| greedy search             | 2.77       | 7.07       | --epoch 30, --avg 13, --max-duration 100 |
| beam search (beam size 4) | 2.76       | 6.97       | --epoch 30, --avg 13, --max-duration 100|
|                           | test-clean | test-other …

Refactor beam search and update results.

---

egs/librispeech/ASR/transducer_stateless/model.py

We added a flag `from_log_softmax` to support label smoothing. This PR fixes the calling of `optimized_transducer.transducer_loss()`.

Fix calling optimized_transducer after new release.

---

icefall/utils.py

Changed the logging INFO from
```
INFO [train.py:529] (0/2) Epoch 11, batch 1200, loss[ctc_loss=0.1767, att_loss=0.3112, loss=0.2843, over 2450 frames.], tot_loss[ctc_loss=0.1494, att_loss=0.2804, loss=0.2542, over 465668.9883888189 frames.], batch size: 7
```
to
```
INFO [train.py:529] (0/2) Epoch 11, batch 1200, loss[ctc_loss=0.1893, att_loss=0.3245, loss=0.2974, over 2450.00 frames.], tot_loss[ctc_loss=0.1494, att_loss=0.2807, loss=0.2544, over 465668.99 frames.], batch size: 7
```

print num_frame as %.2f

---

egs/librispeech/ASR/prepare.sh
egs/librispeech/ASR/tdnn_lstm_ctc/asr_datamodule.py
egs/librispeech/ASR/transducer_stateless/README.md
egs/librispeech/ASR/transducer_stateless/alignment.py
egs/librispeech/ASR/transducer_stateless/compute_ali.py
egs/librispeech/ASR/transducer_stateless/test_compute_ali.py

We assume that `--max-sym-per-frame` is 1, i.e., the model is trained with **modified transducer**.
The alignment results seem to be reasonable compared with the ones from https://github.com/CorentinJ/librispeech-alignments
https://github.com/k2-fsa/icefall/pull/213
The following compares the word alignments for one utterance from `dev-test` with the one from https://github.com/CorentinJ/librispeech-alignments
(Note: The pre-trained model is from https://github.com/k2-fsa/icefall/pull/213)
TODOs:
I am going to save only the framewise alignment for tokens. Since each word begins with the underscore `_` (with unicode `\xe2\x96\x81`, it is straightforward to get the beginning of a word from the framewise alignment. As there is no silence token in the BPE model, the starting time of a word is …

Add force alignment for stateless transducer.

---

.github/workflows/run-librispeech-2022-03-12.yml
README.md
egs/librispeech/ASR/README.md
egs/librispeech/ASR/RESULTS.md
egs/librispeech/ASR/pruned_transducer_stateless/beam_search.py
egs/librispeech/ASR/pruned_transducer_stateless/decode.py
egs/librispeech/ASR/pruned_transducer_stateless/export.py
egs/librispeech/ASR/pruned_transducer_stateless/pretrained.py
requirements.txt

Training command
```bash
./pruned_transducer_stateless/train.py \
--world-size 8 \
--num-epochs 60 \
--start-epoch 0 \
--exp-dir pruned_transducer_stateless/exp \
--full-libri 1 \
--max-duration 300 \
--prune-range 5 \
--lr-factor 5 \
--lm-scale 0.25
```
Tensorboard log https://tensorboard.dev/experiment/WKRFY5fYSzaVBHahenpNlA/
Decoding command
```bash
for epoch in 42; do
for avg in 11; do
./pruned_transducer_stateless/decode.py \
--epoch $epoch \
--avg $avg \
--exp-dir ./pruned_transducer_stateless/exp \
--max-duration 100 \
--decoding-method greedy_search \
--max-sym-per-frame 1
done
done
for epoch in 42; do
for avg in 11; do
./pruned_transducer_stateless/decode.py \
--epoch $epoch \
--avg $avg \
--exp-dir ./pruned_transducer_stateless/exp \
--max-duration 100 \
--decoding-method …
```

Add modified beam search for pruned rnn-t.

---

egs/librispeech/ASR/pruned_transducer_stateless/beam_search.py
egs/librispeech/ASR/pruned_transducer_stateless/decode.py
egs/librispeech/ASR/pruned_transducer_stateless/decoder.py

This PR uses the GPU parallel decoding method in https://github.com/k2-fsa/k2/pull/926.
The decoding results and time used are as follows:
I used the same model as https://github.com/k2-fsa/icefall/pull/248. The decoding process can run with the max value of **max-duration=2000**, which means **several hundred streams** for not very long utterances.  You can see in the table, the decoding time seems not affect very much by the `beam`, `max-contexts`,  `max-states` (I think it is because we use a small decoding graph, i.e. k2.trivial_graph). So I suggest to use beam=4, max-contexts=4, max-states=8 here.
As for the WERs, it is not as good as the results in https://github.com/k2-fsa/icefall/pull/248 that decoded with `modified_beam_search`(which is 2.56||6.27).  I think one of the reasons is …

Add fast beam search decoding

---

egs/librispeech/ASR/pruned_transducer_stateless/beam_search.py
egs/librispeech/ASR/pruned_transducer_stateless/decode.py

Now if you use
```bash
--decoding-method greedy_search
--max-sym-per-frame 1
```
in decoding, it will decode in batch mode.
For the following deocoding command
```
./pruned_transducer_stateless/decode.py \
--epoch 99 \
--avg 1 \
--exp-dir ./pruned_transducer_stateless/exp \
--max-duration 2000 \
--decoding-method greedy_search \
--max-sym-per-frame 1
```
The output is given below:
**note**: Don't be confused by `epoch-99.pt`, it is just a symlink to the pretrained model from https://github.com/k2-fsa/icefall/pull/248
You can see that the total time in decoding test-clean and test-other is less than 1 minute. The RTF is roughly computed as below:
```
>>> 60 / ((5.3 + 5.4)*60*60)
0.001557632398753894
```
(test-clean has 5.4 hours of data and test-other has 5.3 hours)

Implement greedy search in batch mode for transducer decoding.

---

egs/librispeech/ASR/pruned_transducer_stateless/beam_search.py
egs/librispeech/ASR/pruned_transducer_stateless/decode.py
egs/librispeech/ASR/pruned_transducer_stateless/pretrained.py
requirements-ci.txt

For the following decoding command:
```bash
./pruned_transducer_stateless/decode.py \
--epoch $epoch \
--avg $avg \
--exp-dir ./pruned_transducer_stateless/exp \
--max-duration 2000 \
--decoding-method modified_beam_search \
--beam-size 4
```
The output is
`epoch-99.pt` is a symlink to the pretrained model from https://github.com/k2-fsa/icefall/pull/248
Note:
- The total decoding time for test-clean and test-other with this PR is about 4 minutes.
- While the total time for [#248](https://github.com/k2-fsa/icefall/pull/248) is 9 minutes

Support modified beam search in batch mode.

---

egs/librispeech/ASR/pruned_transducer_stateless/train.py

It restores the sampler's state dict only if it loads a checkpoint that was saved during the middle of an epoch.

More fixes to the checkpoint code.

---

icefall/diagnostics.py

Is "torch.eigs" a typo of "torch.eig"? 
BTW, according to https://pytorch.org/docs/1.11/generated/torch.eig.html?highlight=torch%20eig#torch.eig, it's better to use "torch.linalg.eigvals".

fix typo of torch.eig

---

egs/librispeech/ASR/pruned_transducer_stateless/train.py
egs/librispeech/ASR/tdnn_lstm_ctc/asr_datamodule.py
egs/librispeech/ASR/transducer/train.py
egs/librispeech/ASR/transducer_lstm/train.py
egs/librispeech/ASR/transducer_stateless/conformer.py
egs/librispeech/ASR/transducer_stateless/train.py
egs/librispeech/ASR/transducer_stateless_multi_datasets/asr_datamodule.py
egs/librispeech/ASR/transducer_stateless_multi_datasets/train.py

Also, suppress the following torch warnings about division by truncation:
```
transducer_stateless/conformer.py:113: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode=
'trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
lengths = ((x_lens - 1) // 2 - 1) // 2
transducer_stateless/train.py:422: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To …
```

Set the seed for dataloader.

---

egs/librispeech/ASR/tdnn_lstm_ctc/asr_datamodule.py
egs/librispeech/ASR/transducer_stateless_multi_datasets/asr_datamodule.py

From 
https://pytorch.org/docs/stable/data.html
This PR fixes the following error during DDP training:
```
File "/usr/lib/python3.8/multiprocessing/context.py", line 283, in _Popen
return Popen(process_obj)
File "/usr/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
super().__init__(process_obj)
File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
self._launch(process_obj)
File "/usr/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 47, in _launch
reduction.dump(process_obj, fp)
File "/usr/lib/python3.8/multiprocessing/reduction.py", line 60, in dump
ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'LibriSpeechAsrDataModule.train_dataloaders.<locals>.worker_init_fn'
```

Don't use a lambda for dataloader's worker_init_fn.

---

egs/aishell/ASR/transducer_emformer/asr_datamodule.py
egs/aishell/ASR/transducer_emformer/decoder.py
egs/aishell/ASR/transducer_emformer/emformer.py
egs/aishell/ASR/transducer_emformer/encoder_interface.py
egs/aishell/ASR/transducer_emformer/joiner.py
egs/aishell/ASR/transducer_emformer/model.py
egs/aishell/ASR/transducer_emformer/noam.py
egs/aishell/ASR/transducer_emformer/test_emformer.py
egs/aishell/ASR/transducer_emformer/train.py
egs/librispeech/ASR/pruned_transducer_stateless/beam_search.py
egs/librispeech/ASR/transducer_emformer/asr_datamodule.py
egs/librispeech/ASR/transducer_emformer/beam_search.py
egs/librispeech/ASR/transducer_emformer/decode.py
egs/librispeech/ASR/transducer_emformer/decoder.py
egs/librispeech/ASR/transducer_emformer/emformer.py
egs/librispeech/ASR/transducer_emformer/encoder_interface.py
egs/librispeech/ASR/transducer_emformer/joiner.py
egs/librispeech/ASR/transducer_emformer/model.py
egs/librispeech/ASR/transducer_emformer/noam.py
egs/librispeech/ASR/transducer_emformer/streaming_decode.py
egs/librispeech/ASR/transducer_emformer/subsampling.py
egs/librispeech/ASR/transducer_emformer/test_emformer.py
egs/librispeech/ASR/transducer_emformer/train.py

We `import` Emformer from `torchaudio` directly at present and use it to replace the Conformer model for the current RNN-T setup.

Use Emformer as RNN-T encoder.

---

.flake8
icefall/__init__.py

Modify icefall/__init__.py to import common functions and classes defined in icefall/utils.py. Hence we can directly import them from `icefall` instead of `icefall.utils`.

Modify icefall/__init__.py.

---

egs/librispeech/ASR/pruned_transducer_stateless/decode.py
icefall/checkpoint.py

Assume you have the following checkpoints:
- checkpoint-100.pt, checkpoint-500.pt, checkpoint-1000.pt
- epoch-0.pt, epoch-1.pt, epoch-2.pt, epoch-3.pt
If you want to use `checkpoint-1000.pt and checkpoint-500.pt` for decoding, you can use
```
--iter 1000 --avg 2
```
If you want to use `epoch-3.pt, epoch-2.pt, and epoch-1.pt` for decoding, you can use
```
--epoch 3 --avg 3
```

Support specifying iteration number of checkpoints for decoding.

---

egs/librispeech/ASR/local/validate_manifest.py
egs/librispeech/ASR/prepare.sh

See also https://github.com/k2-fsa/icefall/issues/320#issuecomment-1108728769
> ... as a side note, maybe it makes sense to add a separate script in each recipe that validates the major assumptions about the data (single supervision per cut, supervisions time bounds == cut time bounds, maybe sth text normalization related like compatibility of BPE model with the supervision texts, etc.)
@pzelasko Please have a review.

Validate generated manifest files.

---

egs/librispeech/ASR/pruned_transducer_stateless2/train.py

See https://github.com/k2-fsa/icefall/issues/247#issuecomment-1116929465
> @csukuangfj I am thinking we should just make it the default that it prints out some details of the batch (e.g. dimensions and sentence-lengths at least; or perhaps the entire object), when we get an OOM error. This will make things like this easier to debug.
This PR prints out the T and U of the batch on CUDA OOM and also saves the batch to disk that can be loaded later using `torch.load`.
---
```
2022-05-05 12:33:52,875 INFO [train.py:983] Sanity check -- see if any of the batches in epoch 0 would cause OOM.
2022-05-05 12:33:54,767 ERROR [train.py:1007] Your GPU ran out of memory with the current max_duration setting. We recommend decreasing max_duration
and trying again.
Failing criterion: single_longest_cut …
```

Save batch to disk on OOM.

---

egs/librispeech/ASR/pruned_transducer_stateless3/decode-giga.py

Results for the gigapseech test/dev datasets using the model from #312 trained with `--giga-prob=0.9`.
```
(py38) kuangfangjun:greedy_search$ grep -r -n --color "best for test" log-* | sort -n -k2 | head -n5
log-decode-iter-536000-avg-9-context-2-max-sym-per-frame-1-2022-05-04-10-45-40:17:greedy_search 10.95   best for test
log-decode-iter-456000-avg-11-context-2-max-sym-per-frame-1-2022-05-03-11-08-12:17:greedy_search        10.96   best for test
log-decode-iter-536000-avg-11-context-2-max-sym-per-frame-1-2022-05-04-10-51-41:17:greedy_search        10.96   best for test
log-decode-iter-448000-avg-10-context-2-max-sym-per-frame-1-2022-05-03-11-26-33:17:greedy_search        10.97   best for test
log-decode-iter-544000-avg-9-context-2-max-sym-per-frame-1-2022-05-04-10-32-29:17:greedy_search …
```

Fix decoding for gigaspeech in the libri + giga setup.

---

egs/aishell/ASR/transducer_stateless/export.py

Do some changes for aishell/ASR/transducer_stateless/export.py.

Do some changes for aishell/ASR/transducer stateless/export.py

---

icefall/env.py

Otherwise, it causes problems when loading a checkpoint saved by torch 1.10.0 from torch 1.7.1

Stringify torch.__version__ before serializing it.

---

egs/librispeech/ASR/local/prepare_lang_bpe.py
egs/librispeech/ASR/local/validate_bpe_lexicon.py
egs/librispeech/ASR/prepare.sh

See https://github.com/k2-fsa/icefall/issues/357#issuecomment-1124965360
This PR can avoid the following error mentioned in https://github.com/k2-fsa/icefall/issues/357#issuecomment-1124852457
>Oh, $ and € symbols
they are tokenized in
$ ▁ $
€ ▁ €
in lexicon_disambig.txt
but those symbols do not exist in tokens.txt
I'm gonna look at the lexicon creation, I'm pretty sure there is a mapping to unk somewhere, it's not the first time I have OOV tokens
@armusc  You may find this PR helpful.

Validate that there are no OOV tokens in BPE-based lexicons.

---

egs/aishell/ASR/local/compute_fbank_aishell.py
egs/aishell/ASR/local/process_aidatatang_200zh.py
egs/gigaspeech/ASR/local/compute_fbank_musan.py
egs/librispeech/ASR/local/compute_fbank_librispeech.py
egs/librispeech/ASR/local/compute_fbank_musan.py
egs/spgispeech/ASR/local/compute_fbank_musan.py
egs/tedlium3/ASR/local/compute_fbank_tedlium.py
egs/timit/ASR/local/compute_fbank_timit.py
egs/wenetspeech/ASR/local/preprocess_wenetspeech.py

This fixes an issue that appeared following a recent lhotse change normalizing output path names for recipes (https://github.com/lhotse-speech/lhotse/pull/712). I didn't test all of them (only librispeech incl. musan), but I think it affects all the scripts I changed.

[egs] Add prefix when reading manifests due to recent lhotse changes

---

egs/librispeech/ASR/pruned_stateless_emformer_rnnt2/emformer.py

torchscript in torch 1.6.0 and 1.7.1 complains that it cannot convert list-of-list to bool.
This PR fixes that.

Fix Emformer for torchscript using torch 1.6.0

---

egs/librispeech/ASR/pruned_stateless_emformer_rnnt2/emformer.py

See https://github.com/k2-fsa/icefall/pull/401#discussion_r890071489
Before #401, it threw the following error for torch 1.6.0 and 1.7.1
```
File "/ceph-fj/fangjun/py38-1.6.0/lib/python3.8/site-packages/torch/jit/__init__.py", line 1900, in _construct
init_fn(script_module)
File "/ceph-fj/fangjun/py38-1.6.0/lib/python3.8/site-packages/torch/jit/_recursive.py", line 353, in init_fn
scripted = create_script_module_impl(orig_value, sub_concrete_type, infer_methods_to_compile)
File "/ceph-fj/fangjun/py38-1.6.0/lib/python3.8/site-packages/torch/jit/_recursive.py", line 376, in create_script_module_impl
create_methods_from_stubs(concrete_type, stubs)
File "/ceph-fj/fangjun/py38-1.6.0/lib/python3.8/site-packages/torch/jit/_recursive.py", line 292, in create_methods_from_stubs …
```

Fix exporting emformer with torchscript using torch 1.6.0

---

egs/aishell/ASR/local/compute_fbank_aidatatang_200zh.py
egs/aishell/ASR/local/compute_fbank_aishell.py
egs/librispeech/ASR/local/compute_fbank_librispeech.py
egs/librispeech/ASR/local/compute_fbank_musan.py
egs/spgispeech/ASR/local/compute_fbank_musan.py
egs/spgispeech/ASR/local/compute_fbank_spgispeech.py
egs/timit/ASR/local/compute_fbank_timit.py
egs/yesno/ASR/local/compute_fbank_yesno.py

It seems that there are issues with LilcomChunkyWriter in the multi-threaded scenario.
See
- https://github.com/k2-fsa/icefall/discussions/391#discussioncomment-2870627
- https://github.com/k2-fsa/icefall/discussions/391#discussioncomment-2885434
- https://github.com/lhotse-speech/lhotse/issues/607#issue-1157450209
- https://github.com/lhotse-speech/lhotse/issues/607#issuecomment-1148373507
One advantage of using ChunkedLilcomHdf5Writer is that it does not need to compete for locks in
the case of multiple threads.

Replace LilcomChunkyWriter with ChunkedLilcomHdf5Writer.

---

.github/scripts/run-aishell-pruned-transducer-stateless3-2022-06-20.sh
.github/scripts/run-librispeech-pruned-transducer-stateless5-2022-05-13.sh
requirements-ci.txt
requirements.txt

Someone reports the following error
```
./pruned_transducer_stateless6/export.py --jit=1
File "./pruned_transducer_stateless6/export.py", line 52, in <module>
from train import get_params, get_transducer_model
File "/xxx/k2-fsa/icefall/egs/librispeech/ASR/pruned_transducer_stateless6/train.py", line 80, in <module>
from model import Transducer
File "/xxx/k2-fsa/icefall/egs/librispeech/ASR/pruned_transducer_stateless6/model.py", line 26, in <module>
from quantization.prediction import JointCodebookLoss
ModuleNotFoundError: No module named 'quantization'
```
and he tries to use
```
pip install quantization
```
but failed.
This PR fixes that.

Add multi_quantization  to requirements.txt

---

egs/librispeech/ASR/pruned_transducer_stateless2/beam_search.py
egs/librispeech/ASR/pruned_transducer_stateless3/decode.py

Code from https://github.com/k2-fsa/icefall/pull/365
Results :
```
For test-clean, WER of different settings are:
beam_4.0_max_contexts_8_max_states_32_num_paths_200_nbest_scale_0.5_temperature_1.0_ngram_lm_scale_0	1.99	best for test-clean
beam_4.0_max_contexts_8_max_states_32_num_paths_200_nbest_scale_0.5_temperature_1.0_ngram_lm_scale_0.01	1.99
beam_4.0_max_contexts_8_max_states_32_num_paths_200_nbest_scale_0.5_temperature_1.0_ngram_lm_scale_0.02	2.0
beam_4.0_max_contexts_8_max_states_32_num_paths_200_nbest_scale_0.5_temperature_1.0_ngram_lm_scale_0.1	2.0
beam_4.0_max_contexts_8_max_states_32_num_paths_200_nbest_scale_0.5_temperature_1.0_ngram_lm_scale_-0.02	2.02
beam_4.0_max_contexts_8_max_states_32_num_paths_200_nbest_scale_0.5_temperature_1.0_ngram_lm_scale_0.05	2.03 …
```

[WIP] Rnn-T LM nbest rescoring

---

egs/aishell2/ASR/local/compile_lg.py

I find the `compile_lg.py` is missing from `egs/aishell2/ASR/local`. Maybe @yuekaizhang forgot to add compile_lg.py for aishell2 recipe.

Add compile_lg.py for aishell2 recipe

---

egs/librispeech/ASR/pruned_transducer_stateless2/beam_search.py
egs/librispeech/ASR/pruned_transducer_stateless3/decode.py
icefall/decode.py

The PR adds one decoding methods:
- ```fast_beam_search_with_nbest_rnn_rescoring``` which do a 4-gram rescoring and RNN-LM rescoring
```
For test-clean, WER of different settings are:
beam_4.0_max_contexts_8_max_states_32_num_paths_200_nbest_scale_0.5_temperature_1.0_ngram_lm_scale_0.05_rnn_lm_scale_-0.1	2.02	best for test-clean
beam_4.0_max_contexts_8_max_states_32_num_paths_200_nbest_scale_0.5_temperature_1.0_ngram_lm_scale_0_rnn_lm_scale_-0.1	2.04
beam_4.0_max_contexts_8_max_states_32_num_paths_200_nbest_scale_0.5_temperature_1.0_ngram_lm_scale_0.01_rnn_lm_scale_-0.1	2.04
beam_4.0_max_contexts_8_max_states_32_num_paths_200_nbest_scale_0.5_temperature_1.0_ngram_lm_scale_0.02_rnn_lm_scale_-0.1	2.04
beam_4.0_max_contexts_8_max_states_32_num_paths_200_nbest_scale_0.5_temperature_1.0_ngram_l …
```

Add RNN-LM rescoring in fast beam search

---

.github/scripts/run-librispeech-streaming-pruned-transducer-stateless2-2022-06-26.sh
egs/librispeech/ASR/pruned_transducer_stateless/beam_search.py
egs/librispeech/ASR/pruned_transducer_stateless/decode_stream.py
egs/librispeech/ASR/pruned_transducer_stateless/streaming_beam_search.py
egs/librispeech/ASR/pruned_transducer_stateless/streaming_decode.py
egs/librispeech/ASR/pruned_transducer_stateless2/streaming_beam_search.py
egs/librispeech/ASR/pruned_transducer_stateless2/streaming_decode.py
egs/librispeech/ASR/pruned_transducer_stateless3/streaming_beam_search.py
egs/librispeech/ASR/pruned_transducer_stateless3/streaming_decode.py
egs/librispeech/ASR/pruned_transducer_stateless4/streaming_beam_search.py
egs/librispeech/ASR/pruned_transducer_stateless4/streaming_decode.py

Add modified_beam_search for streaming decode

---

egs/gigaspeech/ASR/local/compute_fbank_gigaspeech_dev_test.py
egs/gigaspeech/ASR/local/compute_fbank_gigaspeech_splits.py
egs/librispeech/ASR/local/compute_fbank_gigaspeech_dev_test.py
egs/librispeech/ASR/local/compute_fbank_gigaspeech_splits.py
egs/spgispeech/ASR/local/compute_fbank_musan.py
egs/spgispeech/ASR/local/compute_fbank_spgispeech.py
egs/wenetspeech/ASR/local/compute_fbank_wenetspeech_dev_test.py
egs/wenetspeech/ASR/local/compute_fbank_wenetspeech_splits.py

@pingfengluo reported the following error this morning, which I have seen before:
```
2022-07-22 04:00:03,436 INFO [train.py:859] Epoch 20, batch 33700, loss[loss=0.1769, simple_loss=0.2527, pruned_loss=0.05054, over 9882.00 frames.], tot_loss[loss=0.203, simple_loss=0.2838, pruned_loss=0.06109, over 1971049.83 frames.], batch size: 91, lr: 1.30e-04
2022-07-22 04:00:03,437 INFO [train.py:859] Epoch 20, batch 33700, loss[loss=0.2009, simple_loss=0.2789, pruned_loss=0.06148, over 9860.00 frames.], tot_loss[loss=0.2019, simple_loss=0.2821, pruned_loss=0.06092, over 1972654.00 frames.], batch size: 145, lr: 1.30e-04
File "conv_emformer_transducer_stateless2/train.py", line 1144, in <module>
main()
File "conv_emformer_transducer_stateless2/train.py", line …
```

Set overwrite=True when extracting features in batches.

---

README.md
egs/wenetspeech/ASR/RESULTS.md
egs/wenetspeech/ASR/local/compile_lg.py
egs/wenetspeech/ASR/prepare.sh
egs/wenetspeech/ASR/pruned_transducer_stateless2/decode.py

When training with the L subset, the WERs are
|                                    |  dev  | test-net | test-meeting | comment                                  |
|------------------------------------|-------|----------|--------------|------------------------------------------|
|          greedy search             | 7.80  | 8.75     | 13.49        | --epoch 10, --avg 2, --max-duration 100  |
| modified beam search (beam size 4) | 7.76  | 8.71     | 13.41        | --epoch 10, --avg 2, --max-duration 100  |
| fast beam search (1best)  | 7.94  | 8.74     | 13.80        | --epoch 10, --avg 2, --max-duration 1500 |
| fast beam search (nbest)  | 9.82  | 10.98    |     16.37   | --epoch 10, --avg 2, --max-duration 600 |
| fast beam search (nbest oracle)  | 6.88 | 7.18    |     11.77   | --epoch …

Add other decoding methods (nbest, nbest oracle, nbest LG) for wenetspeech pruned rnnt2

---

egs/wenetspeech/ASR/local/text2segments.py
egs/wenetspeech/ASR/prepare.sh

1. Add multiprocessing for wenetspeech text segmentation
2. Fix preparing char based lang for wenetspeech

Fix preparing char based lang and add multiprocessing for wenetspeech text segmentation

---

egs/librispeech/ASR/conformer_ctc/train.py
egs/librispeech/ASR/conformer_ctc2/train.py
egs/librispeech/ASR/streaming_conformer_ctc/train.py
egs/librispeech/ASR/tdnn_lstm_ctc/train.py
egs/librispeech/ASR/transducer/train.py
egs/librispeech/ASR/transducer_lstm/train.py
egs/librispeech/ASR/transducer_stateless/train.py
egs/librispeech/ASR/transducer_stateless2/train.py
egs/librispeech/ASR/transducer_stateless_multi_datasets/train.py
icefall/decode.py
icefall/utils.py

This PR is a continuation of https://github.com/k2-fsa/icefall/pull/485, for remaining recipes in librispeech.

fix about tensorboard

---

egs/aishell/ASR/pruned_transducer_stateless3/train.py

Fix an error introduced in #495
When the `aidatatang_200zh` dataset is not used, `aishell_tot_loss` should be used to replace `tot_loss`.
Otherwise, it causes division by zero error.

Fix computing averaged loss in the aishell recipe.

---

egs/wenetspeech/ASR/pruned_transducer_stateless2/train.py

Add function display_and_save_batch in egs/wenetspeech/ASR/pruned_transducer_stateless2/train.py

Add function display_and_save_batch in wenetspeech/pruned_transducer_stateless2/train.py

---

egs/librispeech/ASR/pruned_transducer_stateless2/model.py
egs/librispeech/ASR/pruned_transducer_stateless5/train.py

See
https://github.com/k2-fsa/icefall/pull/396#issuecomment-1207277213
> The pruned loss is inf. @csukuangfj perhaps we should modify the code that sums up the losses, in icefall/icefall/, to filter out inf's and nan's before incorporating them into the sum?
---
Would be nice if someone can help to propagate the changes to other directories.

Filter non-finite losses

---

egs/aidatatang_200zh/ASR/local/compute_fbank_aidatatang_200zh.py
egs/aidatatang_200zh/ASR/prepare.sh
egs/aidatatang_200zh/ASR/pruned_transducer_stateless2/decode.py

some small changes for aidatatang_200zh

some small changes for aidatatang_200zh

---

egs/librispeech/ASR/pruned_transducer_stateless2/optim.py

Add clamping operation in Eve optimizer for all scalar weights to avoid INF loss during training in some scenarios #534 . The clamping range is set to (-10,2).
Note: This change may cause unexpected effect if you resume training from a model that is trained without clamping.

Add clamping operation in Eve optimizer for all scalar weights

---

.github/scripts/run-librispeech-pruned-transducer-stateless3-2022-05-13.sh
egs/librispeech/ASR/pruned_transducer_stateless3/export.py
egs/librispeech/ASR/pruned_transducer_stateless3/onnx_check.py
egs/librispeech/ASR/pruned_transducer_stateless3/onnx_pretrained.py

1. Sherpa-onnx requires projection layers separately. Corresponding issue is [here](https://github.com/k2-fsa/sherpa-onnx/issues/7). 
2. "blank_id/unk_id/context_size" parameters are stored in all_in_one.onnx internally anymore.

exporting projection layers of joiner separately for onnx

---

.github/scripts/run-aishell-pruned-transducer-stateless3-2022-06-20.sh
.github/scripts/run-librispeech-lstm-transducer-stateless2-2022-09-03.yml
.github/scripts/run-librispeech-pruned-transducer-stateless2-2022-04-29.sh
.github/workflows/run-librispeech-lstm-transducer-stateless2-2022-09-03.yml
egs/librispeech/ASR/lstm_transducer_stateless/lstmp.py
egs/librispeech/ASR/lstm_transducer_stateless2/export.py
egs/librispeech/ASR/lstm_transducer_stateless2/lstmp.py
egs/librispeech/ASR/lstm_transducer_stateless2/streaming-ncnn-decode.py
egs/librispeech/ASR/lstm_transducer_stateless2/streaming-onnx-decode.py
egs/librispeech/ASR/lstm_transducer_stateless2/test_lstmp.py
egs/librispeech/ASR/lstm_transducer_stateless3/lstmp.py
egs/librispeech/ASR/pruned_transducer_stateless3/lstmp.py
egs/librispeech/ASR/pruned_transducer_stateless3/scaling_converter.py
egs/wenetspeech/ASR/pruned_transducer_stateless2/lstmp.py

At present, PyTorch does not support exporting LSTM with projection via ONNX.
This PR proposes a workaround for that. Basically, it reimplements LSTM with projection in Python using a class` LSTMP`
and replace `LSTM` with `LSTMP` before exporting the model to ONNX.

Support exporting LSTM with projection to ONNX

---

egs/librispeech/ASR/generate-lm.sh
egs/librispeech/ASR/lstm_transducer_stateless2/decode.py
egs/librispeech/ASR/pruned_transducer_stateless2/beam_search.py
icefall/__init__.py
icefall/ngram_lm.py
test/test_ngram_lm.py

Continuation of : https://github.com/k2-fsa/icefall/pull/609

Add Shallow fusion in modified_beam_search

---

requirements.txt

#630 adds shallow_fusion, which requires kaldifst. This PR adds kaldifst to requirements.txt

Add kaldifst to requirements.txt

---

egs/csj/ASR/.gitignore
egs/csj/ASR/local/compute_fbank_musan.py
egs/csj/ASR/prepare.sh

Sorry for the hassle. 
I've unlinked compute_fbank_musan.py in order to allow manifest-dir and fbank-dir to be passed from the command line

CSJ: Unlink compute_fbank_musan.py

---

egs/librispeech/ASR/lstm_transducer_stateless2/streaming-onnx-decode.py
egs/librispeech/ASR/pruned_transducer_stateless3/onnx_check.py
egs/librispeech/ASR/pruned_transducer_stateless3/test_onnx.py
egs/librispeech/ASR/pruned_transducer_stateless6/model.py
egs/librispeech/ASR/pruned_transducer_stateless6/vq_utils.py
egs/wenetspeech/ASR/pruned_transducer_stateless2/onnx_check.py
egs/wenetspeech/ASR/pruned_transducer_stateless2/onnx_pretrained.py
icefall/__init__.py
icefall/ngram_lm.py
icefall/utils.py
requirements.txt
test/test_ngram_lm.py

List only absolutely needed dependencies in requirements.txt
Print an error when an optional dependency is used and tell the user how to install it.
---
Closes #636

Remove onnx and onnxruntime from requirements.txt

---

egs/librispeech/ASR/pruned_transducer_stateless2/decode.py
egs/librispeech/ASR/pruned_transducer_stateless3/decode.py
egs/librispeech/ASR/pruned_transducer_stateless4/decode.py
egs/librispeech/ASR/pruned_transducer_stateless5/decode.py

I found that there are many insertion errors at the tail of our results when I was debuging why `modified_beam_search` has worse results than `greedy_search`. I think the issue is we padded too much zero frames to the end of acoustic, and this has larger impact on `modified_beam_search`, so I got worse results when decoding with `modified_beam_search`.
```
grep "*->.*)$" errs-test-clean-greedy_search-epoch-25-avg-7-context-2-max-sym-per-frame-1-use-averaged-model.txt
1221-135767-0008-2333-0:        COME THEREFORE AND LET US FLING MUD AT THEM (*->COME)
1284-1180-0022-617-0:   I'M AFRAID I DON'T KNOW MUCH ABOUT THE LAND OF OZ (*->NO)
1320-122612-0014-1500-0:        THE EXAMINATION HOWEVER RESULTED IN NO DISCOVERY (*->HOWEVER)
1580-141083-0018-2474-0:        NOW MISTER (SOAMES->SOLMES) AT …
```

Remove tail padding for non-streaming models

---

docker/README.md
docker/Ubuntu18.04-pytorch1.12.1-cuda11.3-cudnn8/Dockerfile
docker/Ubuntu18.04-pytorch1.7.1-cuda11.0-cudnn8/Dockerfile

- Fix typo in README.md. The correct syntax for mounting volumes is `-v {/path/in/host/machine}:{/path/in/docker}`. 
- Fix torchaudio version so that installing torchaudio does not uninstall the existing PyTorch version. 
Closes https://github.com/k2-fsa/icefall/issues/646#issuecomment-1300776944

fix torchaudio version in dockerfile

---

.github/scripts/run-librispeech-pruned-transducer-stateless2-2022-04-29.sh
.github/scripts/run-librispeech-pruned-transducer-stateless3-2022-04-29.sh
egs/librispeech/ASR/pruned_transducer_stateless/decode.py
egs/librispeech/ASR/pruned_transducer_stateless/decode_stream.py
egs/librispeech/ASR/pruned_transducer_stateless2/beam_search.py
egs/librispeech/ASR/pruned_transducer_stateless2/decode.py
egs/librispeech/ASR/pruned_transducer_stateless3/decode.py
egs/librispeech/ASR/pruned_transducer_stateless4/decode.py
egs/librispeech/ASR/pruned_transducer_stateless5/decode.py

In our previous experiments, we found using `log_add` can get a better result comparing with using `max` when decoding with a general LG graph, #420 gives a detaily analysis.   
Recently, I found that using `max` can also get good results after adding `allow_partial` (default False) option in https://github.com/k2-fsa/k2/pull/1059 
Here is some results of `pruned_transducer_stateless2` (model was downloaded from https://huggingface.co/csukuangfj/icefall-asr-librispeech-pruned-transducer-stateless2-2022-04-29)
| decoding method | before fixing `allow_partial` | after fixing `allow_partial` |
| ---------------------| -------------------- | ------------------ |
| fast_beam_search_LG |    6.53 & 10.21 |  2.84 & 6.08 |
| fast_beam_search_nbest_LG | 2.84 & 6.0 |  2.84 & 5.98 |
**Note:** …

Add fast_beam_search_LG

---

icefall/utils.py

Here https://github.com/k2-fsa/icefall/blob/master/egs/librispeech/ASR/pruned_transducer_stateless2/conformer.py#L159, we assert `x.size(0) == lengths.max().item() `. It's correct during training time. However, when I tried to send multiple audios from different clients, to dynamic batch the requests, I padded all audios to the nearest 5 before sending them. Then it would cause an error if x.size(0) > mask.size(-1) (for attention scores masking).
This PR fixed the error and we need to use mask = make_pad_mask(lengths, x.size(0)) when dynamic batch with onnx or jit.

fix mask errors when padding audios

---

egs/librispeech/ASR/local/filter_cuts.py
egs/librispeech/ASR/pruned_transducer_stateless7/train.py
egs/librispeech/ASR/pruned_transducer_stateless7/zipformer.py
egs/librispeech/ASR/pruned_transducer_stateless8/train.py

Refer: https://github.com/k2-fsa/icefall/issues/603#issuecomment-1316136756
The output length is given as `T = ((N - 7) // 2 + 1) // 2`. For training, we should ensure that cuts are filtered to remove the ones for which S (number of BPE tokens) is smaller than T. This can be done using, for instance:
```python
def _remove_short_and_long_utt(c: Cut):
if c.duration < 0.1 or c.duration > 25.0:
return False
T = ((c.num_frames - 7) // 2 + 1) // 2
tokens = sp.encode(c.supervisions[0].text, out_type=str)
return T >= len(tokens)
cuts = cuts.filter(_remove_short_and_long_utt)
```

Zipformer output length

---

egs/librispeech/ASR/pruned_transducer_stateless5/export.py
egs/librispeech/ASR/pruned_transducer_stateless5/lstmp.py
egs/librispeech/ASR/pruned_transducer_stateless5/scaling_converter.py

Fix the failure of converting models to torch.jit.script
The conversion command is :
```
./pruned_transducer_stateless5/export.py \
--exp-dir ./pruned_transducer_stateless5/exp \
--bpe-model data/lang_bpe_500/bpe.model \
--epoch 20 \
--avg 10 \
--jit 1
```

Pruned transducer stateless5 for LibriSpeech

---

egs/librispeech/ASR/pruned_transducer_stateless7/optim.py
egs/librispeech/ASR/pruned_transducer_stateless7/train.py

fixing issue https://github.com/k2-fsa/icefall/issues/697
The main idea is passing **names** of each `batch` parameters through various functions.
An option `"--show-dominant-parameters"` is added,   `True` for debugging and `False` for normal-case.
`param_rms` is updated with `p` in function `ScaledAdam::_show_gradient_dominating_parameter `
Does this design meet the requirement?  @danpovey

[ready]show dominant parameters

---

icefall/graph_compiler.py

See #724
Older versions of k2 do not support using a bool tensor for indexing.
The change was introduced by https://github.com/k2-fsa/icefall/pull/669
I suggest that we always add test to cover new changes.

Fix for older versions of k2

---

egs/wenetspeech/ASR/pruned_transducer_stateless5/export.py
egs/wenetspeech/ASR/pruned_transducer_stateless5/lstmp.py
egs/wenetspeech/ASR/pruned_transducer_stateless5/scaling_converter.py

apply `convert_scaled_to_non_scaled` to wenet pruned_transducer_stateless5 model when using jit export as @csukuangfj   [suggested](https://github.com/k2-fsa/icefall/issues/733#issuecomment-1337014509), I've exported models from [here](https://huggingface.co/luomingshuang/icefall_asr_wenetspeech_pruned_transducer_stateless5_streaming) and successfully ran the cpu_jit model in sherpa.

fix wenet stateless5 jit export error

---

egs/librispeech/ASR/pruned_transducer_stateless7/scaling.py

Fix for memory usage... in pruned_transducer_stateless7/scaling.py, when _compute_scale_factor is called, it should be called with x.detach(), not x.

fix for memory usage in pruned_transducer_stateless7/scaling.py

---

egs/wenetspeech/ASR/pruned_transducer_stateless2/train.py
egs/wenetspeech/ASR/pruned_transducer_stateless5/train.py

In pruned RNN-T, it  require that T >= S where T is the number of feature frames after subsampling and S is the number of tokens in the utterance filter the case of T <  S  for training data.

 Filter the training data of T <  S  for Wenet train recipe

---

egs/librispeech/ASR/prepare.sh

Avoid re-generating `librispeech_cuts_train-all-shuf.jsonl.gz` if it exists.

small fixes to prepare.sh

---

egs/librispeech/ASR/distillation_with_hubert.sh
egs/librispeech/ASR/pruned_transducer_stateless6/vq_utils.py
egs/librispeech/ASR/transducer_lstm/train.py

This PR solves https://github.com/k2-fsa/icefall/issues/779.
Due to the change of naming conventions in lhotse, the old codebook indexes can not be merged with the original training manifest. The newly generated codebook index uses lhotse version of 1.11.0. Please re-run your `prepare.sh` with the same version before proceeding with `distillation_with_hubert.sh` to avoid the potential ID mismatch problem.

Fix distillation with HuBERT

---

egs/librispeech/ASR/pruned_transducer_stateless7_ctc/train.py
egs/librispeech/ASR/pruned_transducer_stateless7_ctc_bs/train.py

Zipformer has a slightly different way to [filter out](https://github.com/k2-fsa/icefall/blob/05dfd5e630d525dcc8828feba4d9daf6624af319/egs/librispeech/ASR/pruned_transducer_stateless7/train.py#L1032) the short utterances. This PR adds the same logic for `pruned_transducer_stateless7_ctc` and `pruned_transducer_stateless7_ctc_bs` models.

check for utterance length after subsampling in Zipformer models

---

egs/librispeech/ASR/pruned_transducer_stateless7/train.py
icefall/utils.py

During training, for the uneven-sized batch, the total duration after padding would possibly cause OOM. Hence, for each batch, which is sorted descendingly by length, we simply drop the last few shortest samples, so that the retained total frames (after padding) would not exceed `allow_max_frames`:
`allow_max_frames = int(max_frames * (1.0 + allow_excess_duration_ratio))`,
where `max_frames = max_duration * 1000 // frame_shift_ms`.
We set allow_excess_duration_ratio=0.1.

Filter uneven-sized batch 

---

egs/librispeech/ASR/pruned_transducer_stateless7/zipformer.py
egs/librispeech/ASR/pruned_transducer_stateless7_streaming/zipformer.py

A few simple edits on the comments of zipformer, which I found to have helped in my understanding of the codes.
On particular point which I'm not sure - I couldn't find `zipformer_subsampling_factor` anywhere in the codes, so I suspect it's wrong. However, I couldn't understand where (or why) exactly the mask values were repeated. Anyhow I suspect that it's `zipformer_downsampling_factor`, so that was what I edited to.

Edit Zipformer Comments

---

egs/librispeech/ASR/streaming_conformer_ctc/train.py
egs/librispeech/ASR/transducer_lstm/train.py

Fix bug in streaming_conformer_ctc egs 
```
File "/proj/xcdhdstaff1/bokangz/project/k2/icefall/egs/librispeech/ASR/streaming_conformer_ctc/train.py", line 648, in run                                      
train_dl = librispeech.train_dataloaders()                                                                                                                    
TypeError: train_dataloaders() missing 1 required positional argument: 'cuts_train'
```

Fix bug in streaming_conformer_ctc egs 

---

docs/source/recipes/Non-streaming-ASR/librispeech/zipformer_ctc_blankskip.rst
egs/librispeech/ASR/RESULTS.md
egs/librispeech/ASR/pruned_transducer_stateless7_ctc_bs/ctc_guide_decode_bs.py
egs/librispeech/ASR/pruned_transducer_stateless7_ctc_bs/lconv.py
egs/librispeech/ASR/streaming_conformer_ctc/train.py

Include:
egs/librispeech/ASR/pruned_transducer_stateless7_ctc_bs/ctc_guide_decode_bs.py filename && content(comments)
egs/librispeech/ASR/result.md content
docs/source/recipes/Non-streaming-ASR/librispeech/zipformer_ctc_blankskip.rst content
[icefall-asr-librispeech-pruned_transducer_stateless7_ctc_bs-2023-01-29/tree/main/exp/decode.sh](https://huggingface.co/yfyeung/icefall-asr-librispeech-pruned_transducer_stateless7_ctc_bs-2023-01-29) content

Fix filename ctc_guild_decode_bs.py -> ctc_guide_decode_bs.py

---

.github/scripts/run-librispeech-pruned-transducer-stateless7-streaming-2022-12-29.sh
.github/workflows/run-librispeech-2022-12-29-stateless7-streaming.yml
egs/librispeech/ASR/pruned_transducer_stateless7_streaming/export.py
egs/librispeech/ASR/pruned_transducer_stateless7_streaming/onnx_model_wrapper.py
egs/librispeech/ASR/pruned_transducer_stateless7_streaming/zipformer.py
requirements-ci.txt

There are total 7 * (2+4+3+2+4) state tensors for onnx input, which is too much. I reduced the number of state tensors to four: len_cache, avg_cache, attn_cache(include cached_key, cached_val1, cached_val2), cnn_cache(include cached_conv1, cached_conv2) by adding a wrapper model on zipfomer.

Add streaming onnx export for zipformer

---

egs/librispeech/ASR/local/validate_manifest.py

- modifying the validation script
- the Supervision start is relative to Cut
- let's assume the data is prepared with 'trim-to-supervision' (i.e. Supervision.begin is close to 0.0)
- the end of supervision should not fall out of cut
- a tolerance of 2ms is itroduced
- finally, the validation 'validate_for_asr' from 'lhotse.dataset.speech_recognition' is performed
- this script will be generic also for imported kaldi data folders (for both types 'one segment per wav' and 'many segments per wav')
- actually I am building a generic recipe for training from imported kaldi data folders
- would it be interesting to contribute it to icefall ?

Librispeech, validate_manifest.py

---

egs/tal_csasr/ASR/prepare.sh

The following issues were resolved in this submission：
- the description of the tal_csasr directory
- Execute prepare.sh again, stopping at step 0
Additional issues:
python==3.8
When I install `jieba==0.42.1` in my environment it throws an error as shown in https://github.com/fxsjy/jieba/issues/920, I solve it by `python -m pip install paddlepaddle==2.2.2 -i https:// mirror.baidu.com/pypi/simple`

fix tal_csasr data pre-processing

---

.github/scripts/test-ncnn-export.sh
egs/librispeech/ASR/conv_emformer_transducer_stateless2/export-for-ncnn.py
egs/librispeech/ASR/lstm_transducer_stateless2/export-for-ncnn.py
egs/librispeech/ASR/pruned_transducer_stateless7/decoder.py
egs/librispeech/ASR/pruned_transducer_stateless7/joiner.py
egs/librispeech/ASR/pruned_transducer_stateless7/scaling_converter.py
egs/librispeech/ASR/pruned_transducer_stateless7_streaming/README.md
egs/librispeech/ASR/pruned_transducer_stateless7_streaming/export-for-ncnn-zh.py
egs/librispeech/ASR/pruned_transducer_stateless7_streaming/export-for-ncnn.py
egs/librispeech/ASR/pruned_transducer_stateless7_streaming/streaming-ncnn-decode.py
egs/librispeech/ASR/pruned_transducer_stateless7_streaming/train2.py
egs/librispeech/ASR/pruned_transducer_stateless7_streaming/zipformer.py
egs/librispeech/ASR/pruned_transducer_stateless7_streaming/zipformer2.py

This pull-request supports exporting [`streaming Zipformer`](https://github.com/k2-fsa/icefall/tree/master/egs/librispeech/ASR/pruned_transducer_stateless7_streaming) to [ncnn](https://github.com/tencent/ncnn/) so that we can use it in
[sherpa-ncnn](https://github.com/csukuangfj/sherpa-ncnn)
Two exported models can be found at
- Bilingual (Chinese + English): https://huggingface.co/csukuangfj/sherpa-ncnn-streaming-zipformer-bilingual-zh-en-2023-02-13
- English: https://huggingface.co/csukuangfj/sherpa-ncnn-streaming-zipformer-en-2023-02-13

Export streaming zipformer to ncnn

---

LICENSE

The license is from
https://www.apache.org/licenses/LICENSE-2.0
We use
```
https://www.apache.org/licenses/LICENSE-2.0.txt
```

Use standard apache 2.0 license

---

egs/librispeech/ASR/RESULTS.md
egs/librispeech/ASR/pruned_transducer_stateless/decoder.py
egs/librispeech/ASR/pruned_transducer_stateless2/decoder.py
egs/librispeech/ASR/pruned_transducer_stateless7/decoder.py

Someone mentioned in #923 that the non-streaming Transducer models tend to emit the first non-blank symbol at the very beginning. This PR alleviates this issue by removing the `padding_idx` in the decoder. Here are some results of `pruned_transducer_stateless7` on LibriSpeech:
| model | test-clean | test-other | average first symbol time (ms) |
|--------|-------------|------------|-------------------------------|
| `padding_idx=0` | 2.19 | 5.16 |  7.6 |
| `padding_idx=None` | 2.22  | 5.14  |  127   |
If someone needs this model, I can upload it to huggingface.

Fix padding_idx

---

.github/workflows/test.yml
egs/librispeech/ASR/transducer/test_rnn.py

Due to the random numbers in test_rnn.py, the ci-test has a certain probability of failure.
In PR #934, I restricted the range of random numbers, but that didn't always work.

Ban the test_rnn.py in ci-test

---

egs/wenetspeech/ASR/local/compute_fbank_wenetspeech_dev_test.py
egs/wenetspeech/ASR/pruned_transducer_stateless2/asr_datamodule.py
egs/wenetspeech/ASR/pruned_transducer_stateless2/decode.py
egs/wenetspeech/ASR/pruned_transducer_stateless5/decode.py

I revisited the decoding speed issue of wenetspeech recipes.  There is no big improvement of speed in this pull request, I just make it simpler, webdataset works fine but it is no need to use it.
The table below shows the RTFs of different storge types of dumped features,  the baseline is from our [decoding paper](https://arxiv.org/pdf/2211.00484.pdf), you can see `LilcomHdf5Writer` is farely slower than the other two, `LilcomHdf5Writer + webdataset` behaves similar to `LilcomChunkWriter` (webdataset actually re-dump the features). I change the storage type to `LilcomChunkWriter` in this PR and also other minor fixes.
I used the `test-net` dataset which has 23 hours of audio, the number in brackets are the decoding time.
Decoding method | RTF (LilcomHdf5Writer) | RTF (LilcomHdf5Writer + …

Fix wenetspeech decoding speed

---

egs/librispeech/ASR/pruned_transducer_stateless7/zipformer.py

this if-branch can't trace in onnx-exporting when we use tensor which T-dim is an even number , throw RuntimeError when we run the onnx model :
> The input tensor cannot be reshaped to the requested shape. Input shape:{219,1,384}, requested shape:{110,2,1,384}
even though it can export successfully without any error
we can allow he number of pads to be 0 to make this an unconditional execution.

remove if-branch at downsample pad in zipformer for onnx-export compatibility

---

egs/librispeech/ASR/pruned_transducer_stateless2/beam_search.py
egs/librispeech/ASR/pruned_transducer_stateless7/alignment.py
egs/librispeech/ASR/pruned_transducer_stateless7/compute_ali.py
egs/librispeech/ASR/pruned_transducer_stateless7/test_compute_ali.py
icefall/utils.py

This PR aims to support getting forced-alignments for transducer models. It is modified from the function `modified_beam_search` in `beam_search.py`. We assume that the maximum number of sybmols per frame is 1. The best alignment in the k-beams is used as the result. We will get both word-level alignments and token-level alignments. 
It is based on https://github.com/k2-fsa/icefall/pull/239, but it supports batch-wise computation.

Support batch-wise forced-alignment 

---

egs/librispeech/ASR/pruned_transducer_stateless/decode.py
egs/librispeech/ASR/pruned_transducer_stateless2/conformer.py
egs/librispeech/ASR/pruned_transducer_stateless2/decode.py
egs/librispeech/ASR/pruned_transducer_stateless3/decode.py
egs/librispeech/ASR/pruned_transducer_stateless4/decode.py
egs/librispeech/ASR/pruned_transducer_stateless5/decode.py
egs/librispeech/ASR/transducer_stateless/conformer.py

For the streaming conformer models trained with dynamic chunk-wise attention mask, we can validate its performance with full attention using:
```
./pruned_transducer_stateless4/decode.py \
--epoch 17 \
--avg 5 \
--simulate-streaming 1 \
--causal-convolution 1 \
--decode-chunk-size -1 \
--left-context -1 \
--exp-dir pruned_transducer_stateless4/exp \
--max-duration 600 \
--decoding-method greedy_search
```

add option of using full attention for streaming model decoding

---

egs/librispeech/ASR/pruned_transducer_stateless/export-onnx.py
egs/librispeech/ASR/pruned_transducer_stateless/onnx_check.py
egs/librispeech/ASR/pruned_transducer_stateless/onnx_decode.py
egs/librispeech/ASR/pruned_transducer_stateless/onnx_pretrained.py
egs/librispeech/ASR/pruned_transducer_stateless3/onnx_decode.py
egs/librispeech/ASR/pruned_transducer_stateless3/onnx_pretrained.py
egs/librispeech/ASR/pruned_transducer_stateless5/export-onnx.py
egs/librispeech/ASR/pruned_transducer_stateless5/onnx_decode.py
egs/librispeech/ASR/pruned_transducer_stateless7/onnx_decode.py
egs/librispeech/ASR/transducer_stateless/conformer.py

This PR aims to support decoding and computing RTF on test sets with ONNX exported models (e.g., float32 models and int8 models). It also enables us to measure the performance difference between the ONNX float32 model and ONNX quantized int8 model. Currently, it only supports dynamic quantization, with `op_types_to_quantize=["MatMul"]`. 
In `pruned_transducer_stateless`, **normal conformer, trained with LibriSpeech**
- Onnx float, WER = 2.64 & 6.37, RTF=0.038 & 0.038, encoder 339M, decoder 2.0M, joiner 2.0M
- Onnx int8,  WER = 4.81 & 8.89, RTF=0.030 & 0.030, encoder 135M, decoder 1.3M, joiner 507K
In `pruned_transducer_stateless3`, **reworked conformer, trained with LibriSpeech + GigaSpeech**, 
- Onnx float, WER = 2.04 & 4.71, RTF=0.028 & 0.028, encoder 315M, decoder 2.0M, joiner 1003K
- …

support decoding and computing RTF on test sets with onnx models

---

egs/librispeech/ASR/pruned_transducer_stateless7_streaming/export.py
egs/librispeech/ASR/pruned_transducer_stateless7_streaming/zipformer.py

It was causing errors for `jit_trace_export.py`.

Fix torch.jit.script() export for streaming zipformer.

---

egs/librispeech/ASR/pruned_transducer_stateless7_ctc_bs/export_onnx.py
egs/librispeech/ASR/pruned_transducer_stateless7_ctc_bs/onnx_wrapper.py

Hi all,
This PR is to support exporting BS Zipformer models to ONNX, which can be used in Triton Server.
These exported ONNX models can be deployed using Triton in Sherpa. Sherpa link: https://github.com/k2-fsa/sherpa/pull/364
Thanks,
Wen

Support exporting BS Zipformer models to ONNX, used in Triton Server

---

egs/gigaspeech/ASR/pruned_transducer_stateless2/compute_ppl.py
icefall/shared/ngram_entropy_pruning.py

`compute_ppl.py` can compute the perplexity of the giving ngram LM on the specify dataset, usage:
```shell
./pruned_transducer_stateless7/compute_ppl.py \
--ngram-lm-path ./download/lm/3gram_pruned_1e7.arpa
```
`ngram_entropy_pruning` is from kalid `egs/wsj/s5/utils/lang/ngram_entropy_pruning.py`, which is an implementation of ``Entropy-based Pruning of Backoff Language Models''
in the same way as SRILM, usage:
```shell
./ngram_entropy_pruning.py \
-threshold 1e-8 \
-lm download/lm/4gram.arpa \
-write-lm download/lm/4gram_pruned_1e8.arpa
```

Add compute_ppl.py and ngram_entropy_pruning.py

---

icefall/rnn_lm/.gitignore
icefall/rnn_lm/check-onnx-streaming.py
icefall/rnn_lm/check-onnx.py
icefall/rnn_lm/export-onnx.py
icefall/rnn_lm/export-onnx.sh
icefall/rnn_lm/export.py
icefall/rnn_lm/export.sh
icefall/rnn_lm/model.py

```bash
if [ ! -f ./icefall-librispeech-rnn-lm/exp/pretrained.pt ]; then
GIT_LFS_SKIP_SMUDGE=1 git clone https://huggingface.co/ezerhouni/icefall-librispeech-rnn-lm
pushd icefall-librispeech-rnn-lm/exp
git lfs pull --include "pretrained.pt"
ln -s pretrained.pt epoch-99.pt
popd
fi
python3 ./export-onnx.py \
--exp-dir ./icefall-librispeech-rnn-lm/exp \
--epoch 99 \
--avg 1 \
--vocab-size 500 \
--embedding-dim 2048 \
--hidden-dim 2048 \
--num-layers 3 \
--tie-weights 1
```
```bash
./check-onnx.py \
--jit ./icefall-librispeech-rnn-lm/exp/cpu_jit.pt \
--onnx ./icefall-librispeech-rnn-lm/exp/no-state-epoch-99-avg-1.onnx
```
Will test it in [sherpa-onnx](https://github.com/k2-fsa/sherpa-onnx)
---
Note: The first step is to use it to rescore a complete sentence.
---
```bash
-rw-r--r-- 1 …
```

Support exporting RNNLM to ONNX.

---

egs/librispeech/ASR/prepare.sh
egs/librispeech/ASR/prepare_multidataset.sh

`compile_hlg_using_openfst.py` expects `L_disambig.fst` instead of `disambig_L.fst`.

Fix typo in librispeech OpenFST-based HLG preparation script

---

icefall/rnn_lm/check-onnx-streaming.py
icefall/rnn_lm/export-onnx.py
icefall/rnn_lm/export.py
icefall/rnn_lm/model.py

```
GIT_LFS_SKIP_SMUDGE=1 git clone https://huggingface.co/pfluo/k2fsa-zipformer-chinese-english-mixed
pushd k2fsa-zipformer-chinese-english-mixed/exp
git lfs pull --include "rnn-lm-small-text-19.pt"
ln -s pretrained.pt epoch-999.pt
popd
python3 ./export-onnx.py \
--exp-dir ./k2fsa-zipformer-chinese-english-mixed/exp \
--epoch 999 \
--avg 1 \
--vocab-size 6254 \
--embedding-dim 256 \
--hidden-dim 256 \
--num-layers 6 \
--tie-weights 1
```

export score_token interface for onnx-runtime

---

egs/librispeech/ASR/finetune.sh
egs/librispeech/ASR/pruned_transducer_stateless7/decode_gigaspeech.py
egs/librispeech/ASR/pruned_transducer_stateless7/finetune.py

This PR adds an adapting script for recipe pruned_transducer_stateless7.
For adapting already-trained models to new data, we mix 5% of the new/adaptation data with 95% of the original data by [`CutSet.mux` in Lhotse](https://lhotse.readthedocs.io/en/latest/api.html?highlight=mux#lhotse.cut.CutSet.mux) to fine-tune.
Our observation:
- Adapting can preserve the source domain's performance much better than fine-tuning directly on target data. 
- Adapting gets worse performance on the target domain than fine-tuning directly on target data. 
Usage:
```shell
export CUDA_VISIBLE_DEVICES="0,1"
./pruned_transducer_stateless7/finetune.py \
--world-size 2 \
--num-epochs 20 \
--start-epoch 1 \
--exp-dir pruned_transducer_stateless7/exp_giga_finetune \
--subset S \
--use-fp16 1 \
--base-lr 0.005 \ …
```

Add adaption recipe for pruned_transducer_stateless7

---

egs/librispeech/ASR/RESULTS.md

recipe: https://github.com/k2-fsa/icefall/pull/1059

Add docs for Fine-tune with mux

---

egs/librispeech/ASR/pruned_transducer_stateless/profile.py
egs/librispeech/ASR/pruned_transducer_stateless4/profile.py
egs/librispeech/ASR/pruned_transducer_stateless7/profile.py
egs/librispeech/ASR/zipformer/profile.py
icefall/profiler.py
pyproject.toml

This PR adds FLOPS profiler, which is modified from https://github.com/microsoft/DeepSpeed/blob/master/deepspeed/profiling/flops_profiler/profiler.py. 
For a 30-second input, of shape (1, 3000, 80), 
* Conformer encoder, ([pruned_transducer_stateless](https://github.com/k2-fsa/icefall/tree/master/egs/librispeech/ASR/pruned_transducer_stateless)) params: 83.49 M, flops: 221.62 G
* Reworked Conformer encoder, ([pruned_transducer_stateless4](https://github.com/k2-fsa/icefall/tree/master/egs/librispeech/ASR/pruned_transducer_stateless4)) params: 77.36 M, flops: 149.51 G
* Old Zipformer encoder ([pruned_transducer_stateless7](https://github.com/k2-fsa/icefall/tree/master/egs/librispeech/ASR/pruned_transducer_stateless7)), 69.14 M, flops: 96.65 G
* Zipformer encoder …

add flops profiler, support for Zipformer encoder and Conformer encoder

---

.pre-commit-config.yaml

Earlier versions of isort are not compatible with current version of poetry-core. This causes "pre-commit install" to fail. See: https://github.com/PyCQA/isort/issues/2077

Update pre-commit isort package to v5.11.5

---

egs/commonvoice/ASR/prepare.sh

Add verification to ensure that ffpmeg is installed to prevent audio loading errors such as audioread exceptions. NoBackendError

verify have installed ffmpeg

---

egs/librispeech/ASR/pruned_transducer_stateless7/train.py
icefall/utils.py

* Saves precious disk space.
* Convenient to discover best epoch weights by running `ls -l` on the experiment directory.

Use symlinks for best epochs

---

egs/librispeech/ASR/zipformer/zipformer.py

This PR fixes the following error when running the exported model on GPU.
I think it is a PyTorch bug that it does not support `dim=-1` in `torch.chunk` when running on GPU from Python.
```
File "./sherpa/bin/streaming_server.py", line 531, in stream_consumer_task
await loop.run_in_executor(
File "/star-fj/fangjun/open-source/pyenv/versions/3.8.0/lib/python3.8/concurrent/futures/thread.py", line 57, in run
result = self.fn(*self.args, **self.kwargs)
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript, serialized code (most recent call last):
File "code/__torch__.py", line 41, in forward
encoder_states = torch.slice(states, None, -2)
encoder = self.encoder
_8 = (encoder).streaming_forward(x0, x_lens, …
```

Fix running exported model on GPU.

---

egs/librispeech/ASR/zipformer/model.py

If not use CTC/transducer loss, return tensor instead of int.

Fix for diagnostic

---

egs/librispeech/ASR/pruned_transducer_stateless7_streaming/streaming_decode.py

Error is reported after running the command in Usage example, found the small typo

fix small typo

---

egs/librispeech/ASR/zipformer/export-onnx-streaming.py

Note: This is a bug fix.
See also https://github.com/k2-fsa/sherpa-onnx/issues/174#issuecomment-1608739945
With this change the exported model is able to support batch size > 1.
Please re-export your streaming zipformer with this change or re-download the pre-trained models provided by us.

Fix ONNX export of the latest streaming zipformer model.

---

egs/librispeech/ASR/zipformer/export-onnx-streaming.py
egs/librispeech/ASR/zipformer/export-onnx.py

Before the fix:
After the fix:

Support int8 quantization in decoder

---

egs/librispeech/ASR/zipformer/onnx_decode.py
egs/librispeech/ASR/zipformer/onnx_pretrained.py

For the **non-streaming** Zipformer-Transducer model with 65.55 M params trained on librispeech for 40 epochs:
Zipformer | encoder file size | decoder file size | joiner file size | WER | RTF
-- | -- | -- | -- | -- | --
Baseline |   |   |   | 2.23, 4.96 | 
ONNX | 248M | 2.0M | 1003K | 2.23, 4.96 | 0.030, 0.028
ONNX-int8 | 66M | 1.3M | 254K | 2.27, 4.95 | 0.025, 0.026
We used `quantize_dynamic` with `op_types_to_quantize=["MatMul"], weight_type=QuantType.QInt8`

support testing onnx exported model on the test sets

---

egs/librispeech/ASR/zipformer/scaling.py

I've encountered a situation where the last `SwooshR` in `Subsampling.conv` produces inf due to naive `logaddexp` operation for tracing, so this PR is supposed to fix it

Zipformer2 logaddexp onnx safe

---

egs/librispeech/ASR/zipformer/scaling.py

See also https://github.com/k2-fsa/icefall/pull/1157#issuecomment-1615030588
> @danpovey 
> We should actually test whether torch.logaddexp works in jit tracing mode. I think the if-statement was probably added when we had some kind of custom kernel there that wouldn't work in tracing mode.
---
`torch.logaddexp()` works for both `torch.jit.script()` and `torch.jit.trace()`. However, it causes  the following errors for `torch.onnx.export()`
https://github.com/k2-fsa/icefall/blob/98d89463f6840439e5c4902b98df218a45359198/egs/librispeech/ASR/zipformer/scaling.py#L29-L31
---
This PR makes it possible to use `torch.logaddexp()` for `torch.jit.script()` and `torch.jit.trace()` but use an
alternative for `torch.onnx.export()`.
----
The following code
```python3
#!/usr/bin/env python3
import torch …
```

Fix logaddexp for ONNX export

---

egs/librispeech/ASR/zipformer/scaling.py
egs/librispeech/ASR/zipformer/scaling_converter.py

See https://github.com/k2-fsa/icefall/commit/c3e23ec8d2a3ed2547bd94dee7280bd3f193a47e#commitcomment-120481693
@joazoa
Please try this pull request. I have tested it locally that  both `zipformer/export-onnx.py` and `zipformer/export-onnx-streaming.py`  work as expected with this change. Also, the exported non-streaming and streaming models are able to decode files with `onnx_pretrained.py` and `onnx_pretrained-streaming.py`, respectively.

Fix ONNX export for the latest non-streaming zipformer.

---

egs/librispeech/ASR/pruned_transducer_stateless7_streaming/export.py
egs/librispeech/ASR/pruned_transducer_stateless7_streaming/jit_pretrained.py

Fix the following CI
https://github.com/k2-fsa/icefall/actions/runs/5456575719/jobs/9929567946
```
2023-07-04 15:55:08,897 INFO [jit_pretrained.py:243] Decoding started
File "./pruned_transducer_stateless7_streaming/jit_pretrained.py", line 278, in <module>
main()
File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
return func(*args, **kwargs)
File "./pruned_transducer_stateless7_streaming/jit_pretrained.py", line 255, in main
encoder_out, encoder_out_lens = model.encoder(
File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
return forward_call(*input, **kwargs)
RuntimeError: forward() is missing value …
```

Fix zipformer CI test

---

egs/librispeech/ASR/zipformer/jit_pretrained_ctc.py

See also
https://github.com/k2-fsa/icefall/pull/1130/files#r1252475093
It also fixes the following CI
https://github.com/k2-fsa/icefall/actions/runs/5456594778/jobs/9929614654
```
2023-07-04 15:59:40,115 INFO [pretrained_ctc.py:293] Number of model parameters: 65802947
File "./zipformer/pretrained_ctc.py", line 445, in <module>
main()
File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
return func(*args, **kwargs)
File "./zipformer/pretrained_ctc.py", line 296, in main
model.load_state_dict(checkpoint["model"], strict=False)
File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1671, in load_state_dict
raise …
```

Fix CI test for zipformer CTC

---

.github/workflows/run-aishell-2022-06-20.yml
.github/workflows/run-gigaspeech-2022-05-13.yml
.github/workflows/run-librispeech-2022-03-12.yml
.github/workflows/run-librispeech-2022-04-29.yml
.github/workflows/run-librispeech-2022-05-13.yml
.github/workflows/run-librispeech-2022-11-11-stateless7.yml
.github/workflows/run-librispeech-2022-11-14-stateless8.yml
.github/workflows/run-librispeech-2022-12-01-stateless7-ctc.yml
.github/workflows/run-librispeech-2022-12-08-zipformer-mmi.yml
.github/workflows/run-librispeech-2022-12-15-stateless7-ctc-bs.yml
.github/workflows/run-librispeech-2022-12-29-stateless7-streaming.yml
.github/workflows/run-librispeech-conformer-ctc3-2022-11-28.yml
.github/workflows/run-librispeech-lstm-transducer-stateless2-2022-09-03.yml
.github/workflows/run-librispeech-pruned-transducer-stateless3-2022-05-13.yml
.github/workflows/run-librispeech-streaming-transducer-stateless2-2022-06-26.yml
.github/workflows/run-librispeech-streaming-zipformer-2023-05-18.yml
.github/workflows/run-librispeech-transducer-stateless2-2022-04-19.yml
.github/workflows/run-librispeech-zipformer-2023-05-18.yml
.github/workflows/run-librispeech-zipformer-ctc-2023-06-14.yml
.github/workflows/run-pretrained-conformer-ctc.yml
.github/workflows/run-pretrained-transducer-stateless-librispeech-100h.yml
.github/workflows/run-pretrained-transducer-stateless-librispeech-multi-datasets.yml
.github/workflows/run-pretrained-transducer-stateless-modified-2-aishell.yml
.github/workflows/run-pretrained-transducer-stateless-modified-aishell.yml
.github/workflows/run-pretrained-transducer-stateless.yml
.github/workflows/run-pretrained-transducer.yml
.github/workflows/run-wenetspeech-pruned-transducer-stateless2.yml
.github/workflows/run-yesno-recipe.yml

GitHub actions no longer support ubuntu-18.04 and thus lots of CI tests have failed to start. This PR fixes it by using ubuntu-latest.

Fix failed CI tests by replacing ubuntu-18.04 with ubuntu-latest

---

egs/commonvoice/ASR/local/preprocess_commonvoice.py

`re.sub(r"[^a-zA-Z\s]", "", utt).upper()` will remove `'`, for example, `isn't` will be `ISNT` after text normalizetion.

Fix text normalization bug in CommonVoice.

---

.github/workflows/run-yesno-recipe.yml
egs/yesno/ASR/tdnn/decode.py
egs/yesno/ASR/tdnn/export.py
egs/yesno/ASR/tdnn/export_onnx.py
egs/yesno/ASR/tdnn/jit_pretrained.py
egs/yesno/ASR/tdnn/onnx_pretrained.py

This PR adds code to export the tdnn model from the yesno recipe into the following format:
- torchscript via torch.jit.script()
- onnx via torch.onnx.export()
It also provides script to use the exported model for decoding.
- Users should be able to learn how to do data preparation, training, decoding, model export, and deployment
- Since the yesno dataset is quite small, the whole process can be finished in several minutes on CPU, e.g., less than 10 minutes or even less than 5 minutes

Add export script for the yesno recipe.

---

egs/yesno/ASR/tdnn/asr_datamodule.py

Setting `persistent_workers=True` when creating DataLoader removes a significant overhead at the start of each epoch and validation. Thanks to this, it finishes in ~10s vs a couple of minutes.

Speed up yesno training to finish in ~10s on CPU

---

egs/tal_csasr/ASR/pruned_transducer_stateless5/decode.py

In egs/egs/tal_csasr/ASR/pruned_transducer_stateless5/decode.py
original code:
```
save_results(
params=params,
test_set_name=test_set,
results_dict=results_dict,
)
save_results(
params=params,
test_set_name=test_set,
results_dict=zh_results_dict,
)
save_results(
params=params,
test_set_name=test_set,
results_dict=en_results_dict,
)
```
The original code can cause file overwrite problems.
modified code:
```
save_results(
params=params,
test_set_name=test_set,
results_dict=results_dict,
)
save_results(
params=params,
test_set_name=test_set + "-zh",
results_dict=zh_results_dict,
)
save_results(
params=params,
test_set_name=test_set + "-en",
results_dict=en_results_dict,
)
```

modify tal_csasr recipe

---

egs/aishell/ASR/pruned_transducer_stateless7/onnx_pretrained.py
egs/commonvoice/ASR/pruned_transducer_stateless7/onnx_pretrained.py
egs/librispeech/ASR/conv_emformer_transducer_stateless2/onnx_pretrained.py
egs/librispeech/ASR/lstm_transducer_stateless2/onnx_pretrained.py
egs/librispeech/ASR/lstm_transducer_stateless2/streaming-onnx-decode.py
egs/librispeech/ASR/pruned_transducer_stateless3/onnx_pretrained.py
egs/librispeech/ASR/pruned_transducer_stateless3/test_onnx.py
egs/librispeech/ASR/pruned_transducer_stateless5/onnx_pretrained-streaming.py
egs/librispeech/ASR/pruned_transducer_stateless7/test_onnx.py
egs/librispeech/ASR/pruned_transducer_stateless7_ctc_bs/onnx_pretrained.py
egs/librispeech/ASR/pruned_transducer_stateless7_streaming/onnx_pretrained.py
egs/librispeech/ASR/zipformer/onnx_pretrained-streaming.py
egs/librispeech/ASR/zipformer/onnx_pretrained.py
egs/wenetspeech/ASR/pruned_transducer_stateless2/onnx_check.py
egs/wenetspeech/ASR/pruned_transducer_stateless5/onnx_pretrained-streaming.py
egs/wenetspeech/ASR/pruned_transducer_stateless5/onnx_pretrained.py
egs/yesno/ASR/tdnn/onnx_pretrained.py

To fix the following error in CI:
```
E           ValueError: This ORT build has ['AzureExecutionProvider', 'CPUExecutionProvider'] enabled. Since ORT 1.9, you are required to explicitly set the providers parameter when instantiating InferenceSession. For example, onnxruntime.InferenceSession(..., providers=['AzureExecutionProvider', 'CPUExecutionProvider'], ...)
```
Microsoft just released onnxruntime 1.16.0, which breaks the CI. This PR fixes that.

Fix CI tests

---

.github/scripts/run-pre-trained-conformer-ctc.sh
.github/workflows/run-pretrained-conformer-ctc.yml
egs/librispeech/ASR/conformer_ctc/jit_pretrained_decode_with_HL.py
egs/librispeech/ASR/conformer_ctc/jit_pretrained_decode_with_HLG.py
egs/librispeech/ASR/local/prepare_lang_fst.py
egs/librispeech/ASR/prepare.sh

Information about the graphs in OpenFst:
```bash
(py38) kuangfangjun:ASR$ pwd
/root/fangjun/open-source/icefall-2/egs/librispeech/ASR
(py38) kuangfangjun:ASR$ ls -lh data/lang_bpe_500/*.fst
-rw-r--r-- 1 kuangfangjun root 3.9M Sep 26 19:03 data/lang_bpe_500/H.fst
-rw-r--r-- 1 kuangfangjun root  28M Sep 26 18:32 data/lang_bpe_500/HL.fst
-rw-r--r-- 1 kuangfangjun root 334M Sep 26 19:07 data/lang_bpe_500/HLG.fst
```
Please compare it with the graphs in k2
```
(py38) kuangfangjun:ASR$ ls -lh data/lang_bpe_500/*.pt
-rw-r--r-- 1 kuangfangjun root 806M Dec 22  2022 data/lang_bpe_500/HLG.pt
-rw-r--r-- 1 kuangfangjun root  19M Dec 22  2022 data/lang_bpe_500/L.pt
-rw-r--r-- 1 kuangfangjun root 239M Dec 22  2022 data/lang_bpe_500/LG.pt
-rw-r--r-- 1 kuangfangjun root  20M Dec 22  2022 …
```

Support HLG decoding using OpenFst with kaldi decoders

---

.github/scripts/run-pre-trained-ctc.sh
.github/workflows/run-pretrained-ctc.yml
egs/librispeech/ASR/conformer_ctc/jit_pretrained_decode_with_H.py
egs/librispeech/ASR/conformer_ctc/jit_pretrained_decode_with_HL.py
egs/librispeech/ASR/conformer_ctc/jit_pretrained_decode_with_HLG.py
egs/librispeech/ASR/zipformer/export-onnx-ctc.py
egs/librispeech/ASR/zipformer/onnx_pretrained_ctc.py
egs/librispeech/ASR/zipformer/onnx_pretrained_ctc_H.py
egs/librispeech/ASR/zipformer/onnx_pretrained_ctc_HL.py
egs/librispeech/ASR/zipformer/onnx_pretrained_ctc_HLG.py
egs/librispeech/ASR/zipformer/onnx_pretrained_ctc_hlg.py

You can find a pre-trained zipformer CTC model and HLG.fst in the following repo
https://huggingface.co/csukuangfj/sherpa-onnx-zipformer-ctc-en-2023-10-02
```
cd egs/librispeech/ASR
./zipformer/onnx_pretrained_ctc_HLG.py \
--nn-model sherpa-onnx-zipformer-ctc-en-2023-10-02/model.onnx \
--words sherpa-onnx-zipformer-ctc-en-2023-10-02/words.txt \
--HLG ./sherpa-onnx-zipformer-ctc-en-2023-10-02/HLG.fst \
./sherpa-onnx-zipformer-ctc-en-2023-10-02/test_wavs/0.wav  \
./sherpa-onnx-zipformer-ctc-en-2023-10-02/test_wavs/1.wav \
./sherpa-onnx-zipformer-ctc-en-2023-10-02/test_wavs/2.wav 
```
```
cd egs/librispeech/ASR
./zipformer/onnx_pretrained_ctc_HL.py \
--nn-model sherpa-onnx-zipformer-ctc-en-2023-10-02/model.onnx \
--words sherpa-onnx-zipformer-ctc-en-2023-10-02/words.txt \
--HL …
```

Add CTC HLG decoding for zipformer

---

egs/librispeech/ASR/zipformer/optim.py

"It reduces the chance of nan gradients ruining the model, and also it makes the clipping scale actually get applied; there was a bug before, where grad was not used because it was not passed into the other functions directly." -- from Dan

Minor fixes to the `optim.py`

---

egs/librispeech/ASR/pruned_transducer_stateless7/finetune.py
egs/wenetspeech/ASR/pruned_transducer_stateless2/finetune.py

Minor fix for finetuning:
1. Update the model_avg after initializing from the pre-trained model
2. Only match the model prefix if they are exactly the same

Fix model avg

---

icefall/utils.py

1. specifiy -> specify
2. charaters -> characters
3. attribtutes -> attributes

fix typos in icefall/utils.py

---

README.md

This issue resolves #1341 
Fixed the broken link of Deployment with C++ 
Now it redirects to

fixed broken link in Readme file

---

egs/ljspeech/TTS/vits/export-onnx.py
egs/vctk/TTS/vits/export-onnx.py

TTS/VITS training examples assume a hardcoded and constant token count of 79 when exporting the output models to onnx. Although this works for these recipes, I think it's better to make these counts variable for users training on different phone sets.

Update TTS export-onnx.py scripts for handling variable token counts

---

egs/aishell/ASR/pruned_transducer_stateless7_streaming/streaming_decode.py
egs/aishell/ASR/zipformer/streaming_decode.py
egs/csj/ASR/pruned_transducer_stateless7_streaming/streaming_decode.py
egs/gigaspeech/ASR/zipformer/streaming_decode.py
egs/librispeech/ASR/conv_emformer_transducer_stateless/streaming_decode.py
egs/librispeech/ASR/conv_emformer_transducer_stateless2/streaming_decode.py
egs/librispeech/ASR/lstm_transducer_stateless/streaming_decode.py
egs/librispeech/ASR/lstm_transducer_stateless3/streaming_decode.py
egs/librispeech/ASR/pruned_transducer_stateless/streaming_decode.py
egs/librispeech/ASR/pruned_transducer_stateless2/streaming_decode.py
egs/librispeech/ASR/pruned_transducer_stateless3/streaming_decode.py
egs/librispeech/ASR/pruned_transducer_stateless4/streaming_decode.py
egs/librispeech/ASR/pruned_transducer_stateless5/streaming_decode.py
egs/librispeech/ASR/pruned_transducer_stateless7_streaming/streaming_decode.py
egs/librispeech/ASR/pruned_transducer_stateless7_streaming_multi/streaming_decode.py
egs/librispeech/ASR/zipformer/streaming_decode.py
egs/wenetspeech/ASR/pruned_transducer_stateless5/streaming_decode.py
egs/wenetspeech/ASR/zipformer/streaming_decode.py

- some AudioTransform classes produce audio signals out of range [-1,+1]
- Resample produced 1.0079
- The range [-10,+10] was chosen to still be able to reliably distinguish from the [-32k,+32k] signal...
- this is related to : https://github.com/lhotse-speech/lhotse/issues/1254

streaming_decode.py, relax the audio range from [-1,+1] to [-10,+10]

---

egs/librispeech/ASR/zipformer/model.py

`F.ctc_loss` throws error when batch size `N` is `1`. Using `torch.long` as recommended by the documentation fixes this error. 
```python
import torch
N = 1
T = 50
S = 31
V = 20
log_probs = torch.randn(T, N, V, device="cuda:0").log_softmax(2)
targets = torch.randint(1, 20, (S,), device="cuda:0", dtype=torch.int32)
input_lengths = torch.full((N,), T, device="cuda:0", dtype=torch.int32)
target_lengths = torch.tensor([S,], device="cuda:0", dtype=torch.int32)
torch.nn.functional.ctc_loss(log_probs, targets, input_lengths, target_lengths)
```
throws:
```python
RuntimeError: Expected tensor to have CPU Backend, but got tensor with CUDA Backend (while checking arguments for cudnn_ctc_loss)
```

Fixing torch.ctc err

---

egs/gigaspeech/ASR/local/compute_fbank_gigaspeech_splits.py
egs/librispeech/ASR/tdnn_lstm_ctc/asr_datamodule.py
egs/librispeech/ASR/zipformer/decode_gigaspeech.py
egs/librispeech/ASR/zipformer/finetune.py

This is a fine-tuning recipe for Zipformer. The zipformer model is pre-trained on LibriSpeech (see https://huggingface.co/Zengwei/icefall-asr-librispeech-zipformer-2023-05-15) and fine-tuned on GigaSpeech subset S. The results are as follows:
| Model |  GigaSpeech | LibriSpeech |
| -------- | ---------- | --------------- | 
| LS-Zipformer, no fine-tune |  20.06/19.27 | 2.23/4.96 | 
| Giga-Zipformer | 15.33/15.31 | 5.88/15.33 | 
| LS-Zipformer, fine-tune on Giga-S, no mux | 13.31/13.39 | 3.61/7.83 | 
| LS-Zipformer, fine-tune on Giga-S, with mux | 13.18/13.09 | 2.13/4.72 | 
The fine-tuned model achieves much better WER on the target domain.

Fine-tune recipe for Zipformer

---

docs/source/recipes/Finetune/from_supervised/finetune_zipformer.rst
docs/source/recipes/Finetune/index.rst
docs/source/recipes/index.rst

Documentation for finetuning a zipformer model

---

docs/source/recipes/TTS/ljspeech/vits.rst
docs/source/recipes/TTS/vctk/vits.rst
egs/ljspeech/TTS/local/prepare_token_file.py
egs/ljspeech/TTS/local/prepare_tokens_ljspeech.py
egs/ljspeech/TTS/prepare.sh
egs/ljspeech/TTS/vits/export-onnx.py
egs/ljspeech/TTS/vits/infer.py
egs/ljspeech/TTS/vits/test_onnx.py
egs/ljspeech/TTS/vits/tokenizer.py
egs/ljspeech/TTS/vits/train.py
requirements-tts.txt

Suggested by @csukuangfj, for the ljspeech/vits recipe we replace g2p with piper_phonemize (https://github.com/rhasspy/piper-phonemize) in the text tokenizer for deployment purposes. 
Experiments are pending. 
@JinZr might help to merge the changes to the vctk/vits recipe later.

Use piper_phonemize as text tokenizer in ljspeech recipe 

---

egs/librispeech/WSASR/conformer_ctc2/train.py

Based on this [issue](https://github.com/k2-fsa/icefall/issues/1506). I add num-features to input args for train.py to set feature_dim parameter. This parameter setting is based on feature extraction method.

Add num_features to train.py for training WSASR

---

docs/source/recipes/TTS/ljspeech/vits.rst
egs/ljspeech/TTS/README.md
egs/ljspeech/TTS/prepare.sh
egs/ljspeech/TTS/vits/export-onnx.py
egs/ljspeech/TTS/vits/generator.py
egs/ljspeech/TTS/vits/infer.py
egs/ljspeech/TTS/vits/test_model.py
egs/ljspeech/TTS/vits/test_onnx.py
egs/ljspeech/TTS/vits/text_encoder.py
egs/ljspeech/TTS/vits/tokenizer.py
egs/ljspeech/TTS/vits/train.py
egs/ljspeech/TTS/vits/vits.py

low (quality) -> runs faster. high (quality) -> runs slower
---
Need to test it before merging.

Support different tts model types.

---

docs/source/recipes/Finetune/adapter/finetune_adapter.rst
docs/source/recipes/Finetune/index.rst

Documentation for adapter fine-tuning

---

egs/librispeech/ASR/zipformer/export-onnx-streaming.py

- i could also add surfacing of `--feature-dim` into train.py, 
- and also feature extraction had to become configurable in [compute_fbank_librispeech.py](https://github.com/k2-fsa/icefall/blob/master/egs/librispeech/ASR/local/compute_fbank_librispeech.py) and [streaming_decode.py](https://github.com/k2-fsa/icefall/blob/master/egs/librispeech/ASR/zipformer/streaming_decode.py), if you are interested in having the recipe with configurable feature extraction...

allow export of onnx-streaming-models with other than 80dim input features

---

.github/scripts/docker/Dockerfile
.github/scripts/docker/generate_build_matrix.py
.github/scripts/librispeech/ASR/run.sh
egs/librispeech/ASR/zipformer/export-onnx-streaming-ctc.py
egs/librispeech/ASR/zipformer/export-onnx-streaming.py
egs/librispeech/ASR/zipformer/onnx_pretrained_ctc_HLG_streaming.py

Need to install the latest version of kaldifst and kaldi-decoder (v0.2.5)
You can use the model from
https://huggingface.co/csukuangfj/icefall-asr-librispeech-streaming-zipformer-small-2024-03-18
for testing.

Add streaming HLG decoding for zipformer CTC.

---

egs/librispeech/ASR/zipformer_adapter/export-onnx.py
egs/librispeech/ASR/zipformer_adapter/export.py
egs/librispeech/ASR/zipformer_adapter/zipformer.py

Fix adapter in streaming_forward

---

egs/librispeech/ASR/zipformer/zipformer.py

This PR fix a "bug" in `zipformer.py`.  Fortunately, since `float(self.const_attention_rate)` is 0 in eval mode, it did not cause any problem.

fix issue in zipformer.py

---

egs/aishell/ASR/whisper/decode.py
egs/aishell/ASR/whisper/train.py
egs/multi_zh-hans/ASR/whisper/decode.py
egs/multi_zh-hans/ASR/whisper/train.py
egs/speechio/ASR/whisper/decode.py
egs/wenetspeech/ASR/whisper/decode.py
egs/wenetspeech/ASR/whisper/train.py

The base model is missing from the choices list.
Add base choice to model_name argument for whisper model.

Add base choice to model_name argument for whisper model.

---

egs/wenetspeech/KWS/run.sh

Resolve the issue of finetune. py script parameter passing failure due to insufficient addition of \ in wenetspeech KWS run.sh

fix run.sh script in wenetspeech KWS

---

icefall/utils.py

This PR adds functionality to clear existing log handlers before setting up new ones. This feature addresses issues in environments like `torchrun`, where default loggers cannot be easily overridden. By clearing previous handlers, we enable full customization and flexibility of logging configurations, ensuring that setups can be dynamically adjusted without being constrained by pre-existing environment settings.

Clear log handlers before setup

---

egs/audioset/AT/RESULTS.md

The small model has 22m parameters and achieves similar performance as the normal-scaled model. The model has been uploaded to https://huggingface.co/marcoyang/icefall-audio-tagging-audioset-zipformer-small-2024-04-23#/. The onnx model can be found here: https://hf-mirror.com/k2-fsa/sherpa-onnx-zipformer-small-audio-tagging-2024-04-15#/

Add small-scaled model for audio tagging

---

egs/librispeech/SSL/zipformer/hubert_ce.py

This PR fixs the bug in librispeech/SSL, which computes x_lens using padding_mask in a wrong way.
Fortunately, it did not cause any problem.

fix error in length computing

---

icefall/utils.py

From dan, "probably in my version of torch inside setup_dist(), had already set up the logger, and in order to get the setup_logger stuff to work I had to add force=True to the invocation to basic_config. "

Add force=True to logging.basicConfig

---

icefall/utils.py

Since we already have `force=True` to achieve the same logic, explicitly resetting logging is no longer necessary.

Remove duplicate logging initialization logic in utils.py

---

egs/librispeech/ASR/zipformer/scaling.py

This aims to fix the inf issue when the input vector is all-zero.

Initialize BiasNorm bias with small random values

---

icefall/ctc/__init__.py
icefall/ctc/test_utils.py
icefall/ctc/utils.py

Add merge_tokens for ctc forced alignment

---

egs/multi_zh-hans/ASR/RESULTS.md
egs/speechio/ASR/RESULTS.md
egs/speechio/ASR/whisper/decode.py
egs/speechio/ASR/whisper/whisper_decoder_forward_monkey_patch.py

In #1605, we fine-tuned whisper using 14k hours Chinese data. This PR added decoding results for distill-whisper fine-tuning experiment.
Instead of actually using distillation loss for training, the model structure and parameter initialization method from the distill-whisper paper (https://arxiv.org/abs/2311.00430) were adopted: only the first and last layers of the decoder were retained.
Accuracy:
Distill-whisper is slightly worse comparing with norm whisper.   
| Model  | CER (Average SPEECH_IO_TEST_SET 01-26) | Training Set |
| --- | --- | --- |
| **whisper-large-ft-v1** | **4.32%** | multi-hans-zh (about 14k hours) |
| **whisper-large-ft-v1-distill** | **4.71%** | multi-hans-zh (about 14k hours) |
Speed: 
Every decoding step could acclerate about 4x comparing with the original …

add Chinese distill-whisper fine-tuning results 

---

.github/scripts/ksponspeech/ASR/run.sh
.github/workflows/ksponspeech.yml

See also https://github.com/k2-fsa/icefall/pull/1651
CC @whsqkaak

Add CI for ksponspeech

---

egs/librispeech/ASR/zipformer/export-onnx-streaming.py
egs/librispeech/ASR/zipformer/export-onnx.py
requirements.txt

Hi @csukuangfj , @yaozengwei
Exporting zipformer onnx model in FP16
Model is trained in mixed precision, therefore having fp16 shouldn't give any loss
Tested with data, and model accuracy is exactly same as fp32.
cc: https://github.com/k2-fsa/sherpa-onnx/issues/41 , https://github.com/k2-fsa/sherpa-onnx/issues/40

Zipformer Onnx FP16

---

egs/librispeech/ASR/zipformer/scaling.py
egs/librispeech/ASR/zipformer_lora/scaling.py

`grad_scale` in Whiten throws error if it is of type `ScheduledFloat`.

Cast grad_scale in whiten to float

---

icefall/decode.py
test/test_ctc_greedy_search.py

Use torch.unique_consecutive() to avoid reinventing the wheel.
See also #1690

Refactor ctc greedy search.

---

egs/multi_zh-hans/ASR/RESULTS.md
egs/multi_zh-hans/ASR/zipformer/decode.py

Update training results using 14k hours opensource Chinese data with a 750M zipformer. 
The model has got current open model's SOTA for wenetspeech test_meeting set with 5.85% WER.
| Model |  [yuekai/icefall-asr-multi-zh-hans-zipformer-large](https://huggingface.co/yuekai/icefall-asr-multi-zh-hans-zipformer-large)  | [yuekai/icefall-asr-multi-zh-hans-zipformer-xl](https://huggingface.co/yuekai/icefall-asr-multi-zh-hans-zipformer-xl) |
|-------|---------------------------------------------------|-|
| Config | Transducer Greedy Offline| Transducer Greedy Offline  (blank_penalty 0.7)  |
| aishell-1 test | 1.38 | 1.31 |
| aishell-2 test | 3.23 | 3.27 |
| aishell-4 test | 15.36 | 14.64 |
| WenetSpeech test_meeting | 6.26 | 5.85 |
| WenetSpeech tes_net | 7.07 | 6.89 |
( The model reused whisper …

Update Zipformer-xl 700M Results on multi-hans-zh

---

egs/librispeech/ASR/zipformer/ctc_decode.py
egs/librispeech/ASR/zipformer/decode.py
egs/librispeech/ASR/zipformer/streaming_decode.py

THE IDEA
- the idea is to support `--skip-scoring` argument passed to a decoding script
- created for Transducer decoding (non-streaming, streaming) and CTC decoding (non-streaming)
OTHER CHANGES
- also added `--label` for extra label in `streaming_decode.py`
- and also added `set_caching_enabled(True)`
- this has no effect on librispeech, but it leads to faster runtime on DBs with long recordings (assuming `librispeech/zipformer` scripts are the example scripts for other setups)
- replaced some '-' with '_' and vice versa, to get more readable filenames with results
TESTING
- still need to run the code to make sure it works properly (it is meld-ed from other recipe)
- at this point, interested in getting early feedback from you...
Thank you.

librispeech_decode : split `save_results()` -> `save_asr_output()` + `save_wer_results()`

---

egs/libriheavy/ASR/local/prepare_manifest.py
egs/libriheavy/ASR/prepare.sh

Resolves #1716. Add a flag to keep the custom fields in libriheavy manifests. Those fields are needed for PromptASR.

Keep the custom fields in libriheavy manifest

---

egs/audioset/AT/RESULTS.md
egs/audioset/AT/local/compute_weight.py
egs/audioset/AT/prepare.sh
egs/audioset/AT/zipformer/at_datamodule.py
egs/audioset/AT/zipformer/train.py

Weighted sampler is known to improve the mAP of models trained on AudioSet. This PR adds support training Zipformer audio tagging model with weighted sampler. The mAP comparison is below:
| weighted sampler | mAP | Full Audioset iterations| 
| -------------------- | ----- | ------------------- | 
| No | 45.1 |  ~30 round |
| Yes | 46.6 |  ~10 round |
With weighted sampler, we achieve faster and better convergence. The pre-trained model can be downloaded here: https://huggingface.co/marcoyang/icefall-audio-tagging-audioset-zipformer-M-weighted-sampler

Support AudioSet training with weighted sampler 

---

egs/gigaspeech/ASR/prepare.sh

fix https://github.com/k2-fsa/icefall/issues/1728

fix gigaspeech_prepare.sh

---

egs/librispeech/ASR/zipformer/export-onnx-streaming.py
egs/librispeech/ASR/zipformer/zipformer.py

It is to fix the following warning messages when fixing the batch size of the kws model to 1:
```
2024-09-11 14:57:33.363528468 [W:onnxruntime:, graph.cc:108 MergeShapeInfo] Error merging shape info for output. '/downsample/Concat_1_output_0' source:{17,1,128} target:{16,1,128}. Falling back to lenient merge.
2024-09-11 14:57:33.363944876 [W:onnxruntime:, graph.cc:108 MergeShapeInfo] Error merging shape info for output. '/downsample_1/Concat_1_output_0' source:{17,1,128} target:{16,1,128}. Falling back to lenient merge.
2024-09-11 14:57:33.364352529 [W:onnxruntime:, graph.cc:108 MergeShapeInfo] Error merging shape info for output. '/downsample_2/Concat_1_output_0' source:{17,1,128} target:{16,1,128}. Falling back to lenient merge.
2024-09-11 14:57:33.364754380 [W:onnxruntime:, …
```

Fix exporting streaming zipformer models to onnx

---

egs/wenetspeech/KWS/prepare.sh

https://github.com/k2-fsa/icefall/blob/3b257dd5ae79bff99470ec1cbbeaa8fae84f956a/egs/wenetspeech/KWS/prepare.sh#L66
As shown in the figure below, the path of `open-commands->scripts` is incorrect, this MR just fix open-commands path in kws.

fix open-commands path in kws

---

egs/commonvoice/ASR/prepare.sh

Details can be found at:
> There is a bug in CommonVoice(EN) recipe（prepare.sh: line 342 ）：**"text"** is in **"supervisions"**, so it should be extracted by using **jq '.supervisions[].text'** ![image](https://private-user-images.githubusercontent.com/8839139/374822152-79a319b5-bdbc-4256-8f6d-fbfd225afdb8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0NTQxMTksIm5iZiI6MTcyODQ1MzgxOSwicGF0aCI6Ii84ODM5MTM5LzM3NDgyMjE1Mi03OWEzMTliNS1iZGJjLTQyNTYtOGY2ZC1mYmZkMjI1YWZkYjgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDlUMDYwMzM5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1T …

fixed `prepare.sh` for the commonvoice recipe

---

icefall/checkpoint.py

The batch_idx_train save in epoch-*.pt may be different from the batch_idx_train when the model_avg is update. This may cause instability in the decode results, especially when params.avg is small and the train step for an epoch is not very large

Fix the batch_idx_train mismatch for model averaging

---

egs/wenetspeech/ASR/prepare.sh

it use a fixed num_splits 1000 , should be pieces=$(find data/fbank/M_split_${num_splits} -name "cuts_M.*.jsonl.gz")

Fix the fixed num_splits bug

---

egs/librispeech/ASR/zipformer/optim.py

Changes from Dan:
> Guys, I was just running an Icefall training script where I tried to change the learning rate after training it for some time, and it used the original learning rate because it loaded the original scheduler state.  The following would fix it.

Avoid using lr from checkpoint.

---

egs/libriheavy/ASR/local/prepare_manifest.py

Fixes a bug where the shell variable with a False value is passed to Python as a string, causing bool("False") to evaluate as True.

Fix Boolean Conversion Issue from Shell to Python

---

.github/scripts/docker/generate_build_matrix.py

This is to avoid merging PRs like #1814 which break backward compatibility for older versions of PyTorch.

Add torch 1.13 and 2.0 to CI tests

---

.github/scripts/docker/Dockerfile
.github/scripts/ljspeech/TTS/run-matcha.sh
.github/workflows/ljspeech.yml
egs/ljspeech/TTS/README.md
egs/ljspeech/TTS/matcha/export_onnx.py
egs/ljspeech/TTS/vits/utils.py

Please see 
https://huggingface.co/csukuangfj/matcha-icefall-en_US-ljspeech/tree/main
and
https://github.com/k2-fsa/sherpa-onnx/releases/tag/tts-models
---
You can find the doc at
https://k2-fsa.github.io/sherpa/onnx/tts/pretrained_models/matcha.html#matcha-icefall-en-us-ljspeech-american-english-1-female-speaker
--

Publish MatchaTTS onnx models trained with LJSpeech to huggingface

---

egs/librispeech/ASR/zipformer/train.py
icefall/hooks.py

1. Attach the inf-check hooks if the grad scale is getting too small.
2. Add try-catch to avoid OOM in the inf-check hooks.
3. Set warmup_start=0.1 to reduce chances of divergence.

Improve infinity-check

---

egs/wenetspeech/KWS/zipformer/finetune.py

Considering moving the entire if rank == 0 code block outside could cause issues because:
1. If moved above, when continue_finetune is false, the model in copy.deepcopy(model) has not yet called model.load_state_dict().
2. If moved below, when continue_finetune is true, model_avg would come from copy.deepcopy(model) rather than the model_avg saved in the checkpoint.

Fix bug: When resuming training from a checkpoint, model_avg was not assigned, resulting in a None error.

---

egs/wenetspeech/KWS/zipformer/finetune.py

```python
./egs/wenetspeech/KWS/zipformer/finetune.py:664:20: F821 undefined name 'partial'
_encode_text = partial(encode_text, token_table=token_table, params=params)
^
1     F821 undefined name 'partial'
```

fix bug: undefined name 'partial'

---

icefall/utils.py

This PR fixes the following log messages:

Fix logging torch.dtype.

---

egs/librispeech/ASR/zipformer/finetune.py

Fixed a bug in finetune.py related to --use-mux. The original value was 95%, which caused an issue when running finetune --help. By changing it to 95%%, the bug is resolved.

Fix a bug in finetune.py --use-mux
